// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 内容类型
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   * 内容类型
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   * 扩展内容（JSON字符串）
   * </pre>
   *
   * <code>string content_extra = 3;</code>
   * @return The contentExtra.
   */
  java.lang.String getContentExtra();
  /**
   * <pre>
   * 扩展内容（JSON字符串）
   * </pre>
   *
   * <code>string content_extra = 3;</code>
   * @return The bytes for contentExtra.
   */
  com.google.protobuf.ByteString
      getContentExtraBytes();

  /**
   * <pre>
   * 原始消息ID（编辑、引用、转发时使用）
   * </pre>
   *
   * <code>string original_message_id = 4;</code>
   * @return The originalMessageId.
   */
  java.lang.String getOriginalMessageId();
  /**
   * <pre>
   * 原始消息ID（编辑、引用、转发时使用）
   * </pre>
   *
   * <code>string original_message_id = 4;</code>
   * @return The bytes for originalMessageId.
   */
  com.google.protobuf.ByteString
      getOriginalMessageIdBytes();

  /**
   * <pre>
   * 操作类型
   * </pre>
   *
   * <code>string operation_type = 5;</code>
   * @return The operationType.
   */
  java.lang.String getOperationType();
  /**
   * <pre>
   * 操作类型
   * </pre>
   *
   * <code>string operation_type = 5;</code>
   * @return The bytes for operationType.
   */
  com.google.protobuf.ByteString
      getOperationTypeBytes();

  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   * @return Whether the quoteInfo field is set.
   */
  boolean hasQuoteInfo();
  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   * @return The quoteInfo.
   */
  com.acme.im.common.websocket.proto.QuoteInfo getQuoteInfo();
  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   */
  com.acme.im.common.websocket.proto.QuoteInfoOrBuilder getQuoteInfoOrBuilder();

  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   * @return Whether the forwardInfo field is set.
   */
  boolean hasForwardInfo();
  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   * @return The forwardInfo.
   */
  com.acme.im.common.websocket.proto.ForwardInfo getForwardInfo();
  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   */
  com.acme.im.common.websocket.proto.ForwardInfoOrBuilder getForwardInfoOrBuilder();

  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   * @return Whether the editInfo field is set.
   */
  boolean hasEditInfo();
  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   * @return The editInfo.
   */
  com.acme.im.common.websocket.proto.EditInfo getEditInfo();
  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   */
  com.acme.im.common.websocket.proto.EditInfoOrBuilder getEditInfoOrBuilder();

  /**
   * <pre>
   * 回复消息ID
   * </pre>
   *
   * <code>string reply_to_id = 9;</code>
   * @return The replyToId.
   */
  java.lang.String getReplyToId();
  /**
   * <pre>
   * 回复消息ID
   * </pre>
   *
   * <code>string reply_to_id = 9;</code>
   * @return The bytes for replyToId.
   */
  com.google.protobuf.ByteString
      getReplyToIdBytes();

  /**
   * <pre>
   * 提及的用户ID列表（JSON字符串）
   * </pre>
   *
   * <code>string mentions = 10;</code>
   * @return The mentions.
   */
  java.lang.String getMentions();
  /**
   * <pre>
   * 提及的用户ID列表（JSON字符串）
   * </pre>
   *
   * <code>string mentions = 10;</code>
   * @return The bytes for mentions.
   */
  com.google.protobuf.ByteString
      getMentionsBytes();

  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 消息优先级
   * </pre>
   *
   * <code>int32 priority = 12;</code>
   * @return The priority.
   */
  int getPriority();
}
