// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf type {@code com.acme.im.websocket.ChatMessage}
 */
public final class ChatMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.ChatMessage)
    ChatMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessage.newBuilder() to construct.
  private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessage() {
    content_ = "";
    contentType_ = "";
    contentExtra_ = "";
    originalMessageId_ = "";
    operationType_ = "";
    replyToId_ = "";
    mentions_ = "";
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ChatMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.ChatMessage.class, com.acme.im.common.websocket.proto.ChatMessage.Builder.class);
  }

  private int bitField0_;
  public static final int CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息内容
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentType_ = "";
  /**
   * <pre>
   * 内容类型
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public java.lang.String getContentType() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 内容类型
   * </pre>
   *
   * <code>string content_type = 2;</code>
   * @return The bytes for contentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentTypeBytes() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_EXTRA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object contentExtra_ = "";
  /**
   * <pre>
   * 扩展内容（JSON字符串）
   * </pre>
   *
   * <code>string content_extra = 3;</code>
   * @return The contentExtra.
   */
  @java.lang.Override
  public java.lang.String getContentExtra() {
    java.lang.Object ref = contentExtra_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentExtra_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 扩展内容（JSON字符串）
   * </pre>
   *
   * <code>string content_extra = 3;</code>
   * @return The bytes for contentExtra.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentExtraBytes() {
    java.lang.Object ref = contentExtra_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentExtra_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_MESSAGE_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalMessageId_ = "";
  /**
   * <pre>
   * 原始消息ID（编辑、引用、转发时使用）
   * </pre>
   *
   * <code>string original_message_id = 4;</code>
   * @return The originalMessageId.
   */
  @java.lang.Override
  public java.lang.String getOriginalMessageId() {
    java.lang.Object ref = originalMessageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalMessageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始消息ID（编辑、引用、转发时使用）
   * </pre>
   *
   * <code>string original_message_id = 4;</code>
   * @return The bytes for originalMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalMessageIdBytes() {
    java.lang.Object ref = originalMessageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalMessageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_TYPE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object operationType_ = "";
  /**
   * <pre>
   * 操作类型
   * </pre>
   *
   * <code>string operation_type = 5;</code>
   * @return The operationType.
   */
  @java.lang.Override
  public java.lang.String getOperationType() {
    java.lang.Object ref = operationType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operationType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 操作类型
   * </pre>
   *
   * <code>string operation_type = 5;</code>
   * @return The bytes for operationType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperationTypeBytes() {
    java.lang.Object ref = operationType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operationType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTE_INFO_FIELD_NUMBER = 6;
  private com.acme.im.common.websocket.proto.QuoteInfo quoteInfo_;
  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   * @return Whether the quoteInfo field is set.
   */
  @java.lang.Override
  public boolean hasQuoteInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   * @return The quoteInfo.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.QuoteInfo getQuoteInfo() {
    return quoteInfo_ == null ? com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance() : quoteInfo_;
  }
  /**
   * <pre>
   * 引用信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.QuoteInfoOrBuilder getQuoteInfoOrBuilder() {
    return quoteInfo_ == null ? com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance() : quoteInfo_;
  }

  public static final int FORWARD_INFO_FIELD_NUMBER = 7;
  private com.acme.im.common.websocket.proto.ForwardInfo forwardInfo_;
  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   * @return Whether the forwardInfo field is set.
   */
  @java.lang.Override
  public boolean hasForwardInfo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   * @return The forwardInfo.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.ForwardInfo getForwardInfo() {
    return forwardInfo_ == null ? com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance() : forwardInfo_;
  }
  /**
   * <pre>
   * 转发信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.ForwardInfoOrBuilder getForwardInfoOrBuilder() {
    return forwardInfo_ == null ? com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance() : forwardInfo_;
  }

  public static final int EDIT_INFO_FIELD_NUMBER = 8;
  private com.acme.im.common.websocket.proto.EditInfo editInfo_;
  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   * @return Whether the editInfo field is set.
   */
  @java.lang.Override
  public boolean hasEditInfo() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   * @return The editInfo.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.EditInfo getEditInfo() {
    return editInfo_ == null ? com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance() : editInfo_;
  }
  /**
   * <pre>
   * 编辑信息
   * </pre>
   *
   * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.EditInfoOrBuilder getEditInfoOrBuilder() {
    return editInfo_ == null ? com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance() : editInfo_;
  }

  public static final int REPLY_TO_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object replyToId_ = "";
  /**
   * <pre>
   * 回复消息ID
   * </pre>
   *
   * <code>string reply_to_id = 9;</code>
   * @return The replyToId.
   */
  @java.lang.Override
  public java.lang.String getReplyToId() {
    java.lang.Object ref = replyToId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      replyToId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 回复消息ID
   * </pre>
   *
   * <code>string reply_to_id = 9;</code>
   * @return The bytes for replyToId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReplyToIdBytes() {
    java.lang.Object ref = replyToId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      replyToId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MENTIONS_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object mentions_ = "";
  /**
   * <pre>
   * 提及的用户ID列表（JSON字符串）
   * </pre>
   *
   * <code>string mentions = 10;</code>
   * @return The mentions.
   */
  @java.lang.Override
  public java.lang.String getMentions() {
    java.lang.Object ref = mentions_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mentions_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 提及的用户ID列表（JSON字符串）
   * </pre>
   *
   * <code>string mentions = 10;</code>
   * @return The bytes for mentions.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMentionsBytes() {
    java.lang.Object ref = mentions_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mentions_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * 消息标签
   * </pre>
   *
   * <code>repeated string tags = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int PRIORITY_FIELD_NUMBER = 12;
  private int priority_ = 0;
  /**
   * <pre>
   * 消息优先级
   * </pre>
   *
   * <code>int32 priority = 12;</code>
   * @return The priority.
   */
  @java.lang.Override
  public int getPriority() {
    return priority_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, contentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentExtra_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, contentExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalMessageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, originalMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, operationType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getQuoteInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getForwardInfo());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(8, getEditInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(replyToId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, replyToId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mentions_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mentions_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, tags_.getRaw(i));
    }
    if (priority_ != 0) {
      output.writeInt32(12, priority_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, contentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contentExtra_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, contentExtra_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalMessageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, originalMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, operationType_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getQuoteInfo());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getForwardInfo());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getEditInfo());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(replyToId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, replyToId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mentions_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mentions_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, priority_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.ChatMessage)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.ChatMessage other = (com.acme.im.common.websocket.proto.ChatMessage) obj;

    if (!getContent()
        .equals(other.getContent())) return false;
    if (!getContentType()
        .equals(other.getContentType())) return false;
    if (!getContentExtra()
        .equals(other.getContentExtra())) return false;
    if (!getOriginalMessageId()
        .equals(other.getOriginalMessageId())) return false;
    if (!getOperationType()
        .equals(other.getOperationType())) return false;
    if (hasQuoteInfo() != other.hasQuoteInfo()) return false;
    if (hasQuoteInfo()) {
      if (!getQuoteInfo()
          .equals(other.getQuoteInfo())) return false;
    }
    if (hasForwardInfo() != other.hasForwardInfo()) return false;
    if (hasForwardInfo()) {
      if (!getForwardInfo()
          .equals(other.getForwardInfo())) return false;
    }
    if (hasEditInfo() != other.hasEditInfo()) return false;
    if (hasEditInfo()) {
      if (!getEditInfo()
          .equals(other.getEditInfo())) return false;
    }
    if (!getReplyToId()
        .equals(other.getReplyToId())) return false;
    if (!getMentions()
        .equals(other.getMentions())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (getPriority()
        != other.getPriority()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType().hashCode();
    hash = (37 * hash) + CONTENT_EXTRA_FIELD_NUMBER;
    hash = (53 * hash) + getContentExtra().hashCode();
    hash = (37 * hash) + ORIGINAL_MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalMessageId().hashCode();
    hash = (37 * hash) + OPERATION_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getOperationType().hashCode();
    if (hasQuoteInfo()) {
      hash = (37 * hash) + QUOTE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getQuoteInfo().hashCode();
    }
    if (hasForwardInfo()) {
      hash = (37 * hash) + FORWARD_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getForwardInfo().hashCode();
    }
    if (hasEditInfo()) {
      hash = (37 * hash) + EDIT_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getEditInfo().hashCode();
    }
    hash = (37 * hash) + REPLY_TO_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReplyToId().hashCode();
    hash = (37 * hash) + MENTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getMentions().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.ChatMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acme.im.websocket.ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.ChatMessage)
      com.acme.im.common.websocket.proto.ChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.ChatMessage.class, com.acme.im.common.websocket.proto.ChatMessage.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.ChatMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQuoteInfoFieldBuilder();
        getForwardInfoFieldBuilder();
        getEditInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      content_ = "";
      contentType_ = "";
      contentExtra_ = "";
      originalMessageId_ = "";
      operationType_ = "";
      quoteInfo_ = null;
      if (quoteInfoBuilder_ != null) {
        quoteInfoBuilder_.dispose();
        quoteInfoBuilder_ = null;
      }
      forwardInfo_ = null;
      if (forwardInfoBuilder_ != null) {
        forwardInfoBuilder_.dispose();
        forwardInfoBuilder_ = null;
      }
      editInfo_ = null;
      if (editInfoBuilder_ != null) {
        editInfoBuilder_.dispose();
        editInfoBuilder_ = null;
      }
      replyToId_ = "";
      mentions_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      priority_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ChatMessage_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ChatMessage getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ChatMessage build() {
      com.acme.im.common.websocket.proto.ChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ChatMessage buildPartial() {
      com.acme.im.common.websocket.proto.ChatMessage result = new com.acme.im.common.websocket.proto.ChatMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.ChatMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.contentType_ = contentType_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.contentExtra_ = contentExtra_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.originalMessageId_ = originalMessageId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.operationType_ = operationType_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.quoteInfo_ = quoteInfoBuilder_ == null
            ? quoteInfo_
            : quoteInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.forwardInfo_ = forwardInfoBuilder_ == null
            ? forwardInfo_
            : forwardInfoBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.editInfo_ = editInfoBuilder_ == null
            ? editInfo_
            : editInfoBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.replyToId_ = replyToId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.mentions_ = mentions_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.priority_ = priority_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.ChatMessage) {
        return mergeFrom((com.acme.im.common.websocket.proto.ChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.ChatMessage other) {
      if (other == com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance()) return this;
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getContentType().isEmpty()) {
        contentType_ = other.contentType_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getContentExtra().isEmpty()) {
        contentExtra_ = other.contentExtra_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getOriginalMessageId().isEmpty()) {
        originalMessageId_ = other.originalMessageId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getOperationType().isEmpty()) {
        operationType_ = other.operationType_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasQuoteInfo()) {
        mergeQuoteInfo(other.getQuoteInfo());
      }
      if (other.hasForwardInfo()) {
        mergeForwardInfo(other.getForwardInfo());
      }
      if (other.hasEditInfo()) {
        mergeEditInfo(other.getEditInfo());
      }
      if (!other.getReplyToId().isEmpty()) {
        replyToId_ = other.replyToId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getMentions().isEmpty()) {
        mentions_ = other.mentions_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000400;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              contentType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              contentExtra_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              originalMessageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              operationType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getQuoteInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getForwardInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getEditInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              replyToId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              mentions_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 90
            case 96: {
              priority_ = input.readInt32();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object content_ = "";
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息内容
     * </pre>
     *
     * <code>string content = 1;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object contentType_ = "";
    /**
     * <pre>
     * 内容类型
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return The contentType.
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 内容类型
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return The bytes for contentType.
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 内容类型
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容类型
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      contentType_ = getDefaultInstance().getContentType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 内容类型
     * </pre>
     *
     * <code>string content_type = 2;</code>
     * @param value The bytes for contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentType_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object contentExtra_ = "";
    /**
     * <pre>
     * 扩展内容（JSON字符串）
     * </pre>
     *
     * <code>string content_extra = 3;</code>
     * @return The contentExtra.
     */
    public java.lang.String getContentExtra() {
      java.lang.Object ref = contentExtra_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentExtra_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 扩展内容（JSON字符串）
     * </pre>
     *
     * <code>string content_extra = 3;</code>
     * @return The bytes for contentExtra.
     */
    public com.google.protobuf.ByteString
        getContentExtraBytes() {
      java.lang.Object ref = contentExtra_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentExtra_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 扩展内容（JSON字符串）
     * </pre>
     *
     * <code>string content_extra = 3;</code>
     * @param value The contentExtra to set.
     * @return This builder for chaining.
     */
    public Builder setContentExtra(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      contentExtra_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展内容（JSON字符串）
     * </pre>
     *
     * <code>string content_extra = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentExtra() {
      contentExtra_ = getDefaultInstance().getContentExtra();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展内容（JSON字符串）
     * </pre>
     *
     * <code>string content_extra = 3;</code>
     * @param value The bytes for contentExtra to set.
     * @return This builder for chaining.
     */
    public Builder setContentExtraBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      contentExtra_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object originalMessageId_ = "";
    /**
     * <pre>
     * 原始消息ID（编辑、引用、转发时使用）
     * </pre>
     *
     * <code>string original_message_id = 4;</code>
     * @return The originalMessageId.
     */
    public java.lang.String getOriginalMessageId() {
      java.lang.Object ref = originalMessageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalMessageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始消息ID（编辑、引用、转发时使用）
     * </pre>
     *
     * <code>string original_message_id = 4;</code>
     * @return The bytes for originalMessageId.
     */
    public com.google.protobuf.ByteString
        getOriginalMessageIdBytes() {
      java.lang.Object ref = originalMessageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始消息ID（编辑、引用、转发时使用）
     * </pre>
     *
     * <code>string original_message_id = 4;</code>
     * @param value The originalMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalMessageId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始消息ID（编辑、引用、转发时使用）
     * </pre>
     *
     * <code>string original_message_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalMessageId() {
      originalMessageId_ = getDefaultInstance().getOriginalMessageId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始消息ID（编辑、引用、转发时使用）
     * </pre>
     *
     * <code>string original_message_id = 4;</code>
     * @param value The bytes for originalMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalMessageId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object operationType_ = "";
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation_type = 5;</code>
     * @return The operationType.
     */
    public java.lang.String getOperationType() {
      java.lang.Object ref = operationType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operationType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation_type = 5;</code>
     * @return The bytes for operationType.
     */
    public com.google.protobuf.ByteString
        getOperationTypeBytes() {
      java.lang.Object ref = operationType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operationType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation_type = 5;</code>
     * @param value The operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      operationType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation_type = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperationType() {
      operationType_ = getDefaultInstance().getOperationType();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>string operation_type = 5;</code>
     * @param value The bytes for operationType to set.
     * @return This builder for chaining.
     */
    public Builder setOperationTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      operationType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.acme.im.common.websocket.proto.QuoteInfo quoteInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.QuoteInfo, com.acme.im.common.websocket.proto.QuoteInfo.Builder, com.acme.im.common.websocket.proto.QuoteInfoOrBuilder> quoteInfoBuilder_;
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     * @return Whether the quoteInfo field is set.
     */
    public boolean hasQuoteInfo() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     * @return The quoteInfo.
     */
    public com.acme.im.common.websocket.proto.QuoteInfo getQuoteInfo() {
      if (quoteInfoBuilder_ == null) {
        return quoteInfo_ == null ? com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance() : quoteInfo_;
      } else {
        return quoteInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public Builder setQuoteInfo(com.acme.im.common.websocket.proto.QuoteInfo value) {
      if (quoteInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        quoteInfo_ = value;
      } else {
        quoteInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public Builder setQuoteInfo(
        com.acme.im.common.websocket.proto.QuoteInfo.Builder builderForValue) {
      if (quoteInfoBuilder_ == null) {
        quoteInfo_ = builderForValue.build();
      } else {
        quoteInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public Builder mergeQuoteInfo(com.acme.im.common.websocket.proto.QuoteInfo value) {
      if (quoteInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          quoteInfo_ != null &&
          quoteInfo_ != com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance()) {
          getQuoteInfoBuilder().mergeFrom(value);
        } else {
          quoteInfo_ = value;
        }
      } else {
        quoteInfoBuilder_.mergeFrom(value);
      }
      if (quoteInfo_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public Builder clearQuoteInfo() {
      bitField0_ = (bitField0_ & ~0x00000020);
      quoteInfo_ = null;
      if (quoteInfoBuilder_ != null) {
        quoteInfoBuilder_.dispose();
        quoteInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public com.acme.im.common.websocket.proto.QuoteInfo.Builder getQuoteInfoBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getQuoteInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    public com.acme.im.common.websocket.proto.QuoteInfoOrBuilder getQuoteInfoOrBuilder() {
      if (quoteInfoBuilder_ != null) {
        return quoteInfoBuilder_.getMessageOrBuilder();
      } else {
        return quoteInfo_ == null ?
            com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance() : quoteInfo_;
      }
    }
    /**
     * <pre>
     * 引用信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.QuoteInfo quote_info = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.QuoteInfo, com.acme.im.common.websocket.proto.QuoteInfo.Builder, com.acme.im.common.websocket.proto.QuoteInfoOrBuilder> 
        getQuoteInfoFieldBuilder() {
      if (quoteInfoBuilder_ == null) {
        quoteInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.QuoteInfo, com.acme.im.common.websocket.proto.QuoteInfo.Builder, com.acme.im.common.websocket.proto.QuoteInfoOrBuilder>(
                getQuoteInfo(),
                getParentForChildren(),
                isClean());
        quoteInfo_ = null;
      }
      return quoteInfoBuilder_;
    }

    private com.acme.im.common.websocket.proto.ForwardInfo forwardInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.ForwardInfo, com.acme.im.common.websocket.proto.ForwardInfo.Builder, com.acme.im.common.websocket.proto.ForwardInfoOrBuilder> forwardInfoBuilder_;
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     * @return Whether the forwardInfo field is set.
     */
    public boolean hasForwardInfo() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     * @return The forwardInfo.
     */
    public com.acme.im.common.websocket.proto.ForwardInfo getForwardInfo() {
      if (forwardInfoBuilder_ == null) {
        return forwardInfo_ == null ? com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance() : forwardInfo_;
      } else {
        return forwardInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public Builder setForwardInfo(com.acme.im.common.websocket.proto.ForwardInfo value) {
      if (forwardInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        forwardInfo_ = value;
      } else {
        forwardInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public Builder setForwardInfo(
        com.acme.im.common.websocket.proto.ForwardInfo.Builder builderForValue) {
      if (forwardInfoBuilder_ == null) {
        forwardInfo_ = builderForValue.build();
      } else {
        forwardInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public Builder mergeForwardInfo(com.acme.im.common.websocket.proto.ForwardInfo value) {
      if (forwardInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          forwardInfo_ != null &&
          forwardInfo_ != com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance()) {
          getForwardInfoBuilder().mergeFrom(value);
        } else {
          forwardInfo_ = value;
        }
      } else {
        forwardInfoBuilder_.mergeFrom(value);
      }
      if (forwardInfo_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public Builder clearForwardInfo() {
      bitField0_ = (bitField0_ & ~0x00000040);
      forwardInfo_ = null;
      if (forwardInfoBuilder_ != null) {
        forwardInfoBuilder_.dispose();
        forwardInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public com.acme.im.common.websocket.proto.ForwardInfo.Builder getForwardInfoBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getForwardInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    public com.acme.im.common.websocket.proto.ForwardInfoOrBuilder getForwardInfoOrBuilder() {
      if (forwardInfoBuilder_ != null) {
        return forwardInfoBuilder_.getMessageOrBuilder();
      } else {
        return forwardInfo_ == null ?
            com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance() : forwardInfo_;
      }
    }
    /**
     * <pre>
     * 转发信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ForwardInfo forward_info = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.ForwardInfo, com.acme.im.common.websocket.proto.ForwardInfo.Builder, com.acme.im.common.websocket.proto.ForwardInfoOrBuilder> 
        getForwardInfoFieldBuilder() {
      if (forwardInfoBuilder_ == null) {
        forwardInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.ForwardInfo, com.acme.im.common.websocket.proto.ForwardInfo.Builder, com.acme.im.common.websocket.proto.ForwardInfoOrBuilder>(
                getForwardInfo(),
                getParentForChildren(),
                isClean());
        forwardInfo_ = null;
      }
      return forwardInfoBuilder_;
    }

    private com.acme.im.common.websocket.proto.EditInfo editInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.EditInfo, com.acme.im.common.websocket.proto.EditInfo.Builder, com.acme.im.common.websocket.proto.EditInfoOrBuilder> editInfoBuilder_;
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     * @return Whether the editInfo field is set.
     */
    public boolean hasEditInfo() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     * @return The editInfo.
     */
    public com.acme.im.common.websocket.proto.EditInfo getEditInfo() {
      if (editInfoBuilder_ == null) {
        return editInfo_ == null ? com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance() : editInfo_;
      } else {
        return editInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public Builder setEditInfo(com.acme.im.common.websocket.proto.EditInfo value) {
      if (editInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        editInfo_ = value;
      } else {
        editInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public Builder setEditInfo(
        com.acme.im.common.websocket.proto.EditInfo.Builder builderForValue) {
      if (editInfoBuilder_ == null) {
        editInfo_ = builderForValue.build();
      } else {
        editInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public Builder mergeEditInfo(com.acme.im.common.websocket.proto.EditInfo value) {
      if (editInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          editInfo_ != null &&
          editInfo_ != com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance()) {
          getEditInfoBuilder().mergeFrom(value);
        } else {
          editInfo_ = value;
        }
      } else {
        editInfoBuilder_.mergeFrom(value);
      }
      if (editInfo_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public Builder clearEditInfo() {
      bitField0_ = (bitField0_ & ~0x00000080);
      editInfo_ = null;
      if (editInfoBuilder_ != null) {
        editInfoBuilder_.dispose();
        editInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public com.acme.im.common.websocket.proto.EditInfo.Builder getEditInfoBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return getEditInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    public com.acme.im.common.websocket.proto.EditInfoOrBuilder getEditInfoOrBuilder() {
      if (editInfoBuilder_ != null) {
        return editInfoBuilder_.getMessageOrBuilder();
      } else {
        return editInfo_ == null ?
            com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance() : editInfo_;
      }
    }
    /**
     * <pre>
     * 编辑信息
     * </pre>
     *
     * <code>.com.acme.im.websocket.EditInfo edit_info = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.EditInfo, com.acme.im.common.websocket.proto.EditInfo.Builder, com.acme.im.common.websocket.proto.EditInfoOrBuilder> 
        getEditInfoFieldBuilder() {
      if (editInfoBuilder_ == null) {
        editInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.EditInfo, com.acme.im.common.websocket.proto.EditInfo.Builder, com.acme.im.common.websocket.proto.EditInfoOrBuilder>(
                getEditInfo(),
                getParentForChildren(),
                isClean());
        editInfo_ = null;
      }
      return editInfoBuilder_;
    }

    private java.lang.Object replyToId_ = "";
    /**
     * <pre>
     * 回复消息ID
     * </pre>
     *
     * <code>string reply_to_id = 9;</code>
     * @return The replyToId.
     */
    public java.lang.String getReplyToId() {
      java.lang.Object ref = replyToId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        replyToId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 回复消息ID
     * </pre>
     *
     * <code>string reply_to_id = 9;</code>
     * @return The bytes for replyToId.
     */
    public com.google.protobuf.ByteString
        getReplyToIdBytes() {
      java.lang.Object ref = replyToId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        replyToId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 回复消息ID
     * </pre>
     *
     * <code>string reply_to_id = 9;</code>
     * @param value The replyToId to set.
     * @return This builder for chaining.
     */
    public Builder setReplyToId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      replyToId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回复消息ID
     * </pre>
     *
     * <code>string reply_to_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplyToId() {
      replyToId_ = getDefaultInstance().getReplyToId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 回复消息ID
     * </pre>
     *
     * <code>string reply_to_id = 9;</code>
     * @param value The bytes for replyToId to set.
     * @return This builder for chaining.
     */
    public Builder setReplyToIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      replyToId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object mentions_ = "";
    /**
     * <pre>
     * 提及的用户ID列表（JSON字符串）
     * </pre>
     *
     * <code>string mentions = 10;</code>
     * @return The mentions.
     */
    public java.lang.String getMentions() {
      java.lang.Object ref = mentions_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mentions_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 提及的用户ID列表（JSON字符串）
     * </pre>
     *
     * <code>string mentions = 10;</code>
     * @return The bytes for mentions.
     */
    public com.google.protobuf.ByteString
        getMentionsBytes() {
      java.lang.Object ref = mentions_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mentions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 提及的用户ID列表（JSON字符串）
     * </pre>
     *
     * <code>string mentions = 10;</code>
     * @param value The mentions to set.
     * @return This builder for chaining.
     */
    public Builder setMentions(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      mentions_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 提及的用户ID列表（JSON字符串）
     * </pre>
     *
     * <code>string mentions = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMentions() {
      mentions_ = getDefaultInstance().getMentions();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 提及的用户ID列表（JSON字符串）
     * </pre>
     *
     * <code>string mentions = 10;</code>
     * @param value The bytes for mentions to set.
     * @return This builder for chaining.
     */
    public Builder setMentionsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      mentions_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000400;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000400);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息标签
     * </pre>
     *
     * <code>repeated string tags = 11;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <pre>
     * 消息优先级
     * </pre>
     *
     * <code>int32 priority = 12;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <pre>
     * 消息优先级
     * </pre>
     *
     * <code>int32 priority = 12;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {

      priority_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息优先级
     * </pre>
     *
     * <code>int32 priority = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000800);
      priority_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.ChatMessage)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.ChatMessage)
  private static final com.acme.im.common.websocket.proto.ChatMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.ChatMessage();
  }

  public static com.acme.im.common.websocket.proto.ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
    @java.lang.Override
    public ChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.ChatMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

