// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface EditInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.EditInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 原始内容
   * </pre>
   *
   * <code>string original_content = 1;</code>
   * @return The originalContent.
   */
  java.lang.String getOriginalContent();
  /**
   * <pre>
   * 原始内容
   * </pre>
   *
   * <code>string original_content = 1;</code>
   * @return The bytes for originalContent.
   */
  com.google.protobuf.ByteString
      getOriginalContentBytes();

  /**
   * <pre>
   * 编辑原因
   * </pre>
   *
   * <code>string edit_reason = 2;</code>
   * @return The editReason.
   */
  java.lang.String getEditReason();
  /**
   * <pre>
   * 编辑原因
   * </pre>
   *
   * <code>string edit_reason = 2;</code>
   * @return The bytes for editReason.
   */
  com.google.protobuf.ByteString
      getEditReasonBytes();

  /**
   * <pre>
   * 编辑次数
   * </pre>
   *
   * <code>int32 edit_count = 3;</code>
   * @return The editCount.
   */
  int getEditCount();

  /**
   * <pre>
   * 最后编辑时间
   * </pre>
   *
   * <code>int64 last_edit_time = 4;</code>
   * @return The lastEditTime.
   */
  long getLastEditTime();
}
