// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf type {@code com.acme.im.websocket.EditInfo}
 */
public final class EditInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.EditInfo)
    EditInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EditInfo.newBuilder() to construct.
  private EditInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EditInfo() {
    originalContent_ = "";
    editReason_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EditInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EditInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EditInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.EditInfo.class, com.acme.im.common.websocket.proto.EditInfo.Builder.class);
  }

  public static final int ORIGINAL_CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalContent_ = "";
  /**
   * <pre>
   * 原始内容
   * </pre>
   *
   * <code>string original_content = 1;</code>
   * @return The originalContent.
   */
  @java.lang.Override
  public java.lang.String getOriginalContent() {
    java.lang.Object ref = originalContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始内容
   * </pre>
   *
   * <code>string original_content = 1;</code>
   * @return The bytes for originalContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalContentBytes() {
    java.lang.Object ref = originalContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EDIT_REASON_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object editReason_ = "";
  /**
   * <pre>
   * 编辑原因
   * </pre>
   *
   * <code>string edit_reason = 2;</code>
   * @return The editReason.
   */
  @java.lang.Override
  public java.lang.String getEditReason() {
    java.lang.Object ref = editReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      editReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 编辑原因
   * </pre>
   *
   * <code>string edit_reason = 2;</code>
   * @return The bytes for editReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEditReasonBytes() {
    java.lang.Object ref = editReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      editReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EDIT_COUNT_FIELD_NUMBER = 3;
  private int editCount_ = 0;
  /**
   * <pre>
   * 编辑次数
   * </pre>
   *
   * <code>int32 edit_count = 3;</code>
   * @return The editCount.
   */
  @java.lang.Override
  public int getEditCount() {
    return editCount_;
  }

  public static final int LAST_EDIT_TIME_FIELD_NUMBER = 4;
  private long lastEditTime_ = 0L;
  /**
   * <pre>
   * 最后编辑时间
   * </pre>
   *
   * <code>int64 last_edit_time = 4;</code>
   * @return The lastEditTime.
   */
  @java.lang.Override
  public long getLastEditTime() {
    return lastEditTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, originalContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(editReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, editReason_);
    }
    if (editCount_ != 0) {
      output.writeInt32(3, editCount_);
    }
    if (lastEditTime_ != 0L) {
      output.writeInt64(4, lastEditTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, originalContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(editReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, editReason_);
    }
    if (editCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, editCount_);
    }
    if (lastEditTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, lastEditTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.EditInfo)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.EditInfo other = (com.acme.im.common.websocket.proto.EditInfo) obj;

    if (!getOriginalContent()
        .equals(other.getOriginalContent())) return false;
    if (!getEditReason()
        .equals(other.getEditReason())) return false;
    if (getEditCount()
        != other.getEditCount()) return false;
    if (getLastEditTime()
        != other.getLastEditTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORIGINAL_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalContent().hashCode();
    hash = (37 * hash) + EDIT_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getEditReason().hashCode();
    hash = (37 * hash) + EDIT_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getEditCount();
    hash = (37 * hash) + LAST_EDIT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastEditTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.EditInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.EditInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.EditInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.EditInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acme.im.websocket.EditInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.EditInfo)
      com.acme.im.common.websocket.proto.EditInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EditInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EditInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.EditInfo.class, com.acme.im.common.websocket.proto.EditInfo.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.EditInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      originalContent_ = "";
      editReason_ = "";
      editCount_ = 0;
      lastEditTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EditInfo_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EditInfo getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EditInfo build() {
      com.acme.im.common.websocket.proto.EditInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EditInfo buildPartial() {
      com.acme.im.common.websocket.proto.EditInfo result = new com.acme.im.common.websocket.proto.EditInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.EditInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.originalContent_ = originalContent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.editReason_ = editReason_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.editCount_ = editCount_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.lastEditTime_ = lastEditTime_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.EditInfo) {
        return mergeFrom((com.acme.im.common.websocket.proto.EditInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.EditInfo other) {
      if (other == com.acme.im.common.websocket.proto.EditInfo.getDefaultInstance()) return this;
      if (!other.getOriginalContent().isEmpty()) {
        originalContent_ = other.originalContent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEditReason().isEmpty()) {
        editReason_ = other.editReason_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getEditCount() != 0) {
        setEditCount(other.getEditCount());
      }
      if (other.getLastEditTime() != 0L) {
        setLastEditTime(other.getLastEditTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              originalContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              editReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              editCount_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              lastEditTime_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object originalContent_ = "";
    /**
     * <pre>
     * 原始内容
     * </pre>
     *
     * <code>string original_content = 1;</code>
     * @return The originalContent.
     */
    public java.lang.String getOriginalContent() {
      java.lang.Object ref = originalContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始内容
     * </pre>
     *
     * <code>string original_content = 1;</code>
     * @return The bytes for originalContent.
     */
    public com.google.protobuf.ByteString
        getOriginalContentBytes() {
      java.lang.Object ref = originalContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始内容
     * </pre>
     *
     * <code>string original_content = 1;</code>
     * @param value The originalContent to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始内容
     * </pre>
     *
     * <code>string original_content = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalContent() {
      originalContent_ = getDefaultInstance().getOriginalContent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始内容
     * </pre>
     *
     * <code>string original_content = 1;</code>
     * @param value The bytes for originalContent to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalContent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object editReason_ = "";
    /**
     * <pre>
     * 编辑原因
     * </pre>
     *
     * <code>string edit_reason = 2;</code>
     * @return The editReason.
     */
    public java.lang.String getEditReason() {
      java.lang.Object ref = editReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        editReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 编辑原因
     * </pre>
     *
     * <code>string edit_reason = 2;</code>
     * @return The bytes for editReason.
     */
    public com.google.protobuf.ByteString
        getEditReasonBytes() {
      java.lang.Object ref = editReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        editReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 编辑原因
     * </pre>
     *
     * <code>string edit_reason = 2;</code>
     * @param value The editReason to set.
     * @return This builder for chaining.
     */
    public Builder setEditReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      editReason_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑原因
     * </pre>
     *
     * <code>string edit_reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEditReason() {
      editReason_ = getDefaultInstance().getEditReason();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑原因
     * </pre>
     *
     * <code>string edit_reason = 2;</code>
     * @param value The bytes for editReason to set.
     * @return This builder for chaining.
     */
    public Builder setEditReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      editReason_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int editCount_ ;
    /**
     * <pre>
     * 编辑次数
     * </pre>
     *
     * <code>int32 edit_count = 3;</code>
     * @return The editCount.
     */
    @java.lang.Override
    public int getEditCount() {
      return editCount_;
    }
    /**
     * <pre>
     * 编辑次数
     * </pre>
     *
     * <code>int32 edit_count = 3;</code>
     * @param value The editCount to set.
     * @return This builder for chaining.
     */
    public Builder setEditCount(int value) {

      editCount_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 编辑次数
     * </pre>
     *
     * <code>int32 edit_count = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEditCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      editCount_ = 0;
      onChanged();
      return this;
    }

    private long lastEditTime_ ;
    /**
     * <pre>
     * 最后编辑时间
     * </pre>
     *
     * <code>int64 last_edit_time = 4;</code>
     * @return The lastEditTime.
     */
    @java.lang.Override
    public long getLastEditTime() {
      return lastEditTime_;
    }
    /**
     * <pre>
     * 最后编辑时间
     * </pre>
     *
     * <code>int64 last_edit_time = 4;</code>
     * @param value The lastEditTime to set.
     * @return This builder for chaining.
     */
    public Builder setLastEditTime(long value) {

      lastEditTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 最后编辑时间
     * </pre>
     *
     * <code>int64 last_edit_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastEditTime() {
      bitField0_ = (bitField0_ & ~0x00000008);
      lastEditTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.EditInfo)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.EditInfo)
  private static final com.acme.im.common.websocket.proto.EditInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.EditInfo();
  }

  public static com.acme.im.common.websocket.proto.EditInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EditInfo>
      PARSER = new com.google.protobuf.AbstractParser<EditInfo>() {
    @java.lang.Override
    public EditInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EditInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EditInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.EditInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

