// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface EventMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.EventMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>string event_type = 1;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>string event_type = 1;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <pre>
   * 事件名称
   * </pre>
   *
   * <code>string event_name = 2;</code>
   * @return The eventName.
   */
  java.lang.String getEventName();
  /**
   * <pre>
   * 事件名称
   * </pre>
   *
   * <code>string event_name = 2;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <pre>
   * 事件数据（JSON字符串）
   * </pre>
   *
   * <code>string event_data = 3;</code>
   * @return The eventData.
   */
  java.lang.String getEventData();
  /**
   * <pre>
   * 事件数据（JSON字符串）
   * </pre>
   *
   * <code>string event_data = 3;</code>
   * @return The bytes for eventData.
   */
  com.google.protobuf.ByteString
      getEventDataBytes();

  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>string event_source = 4;</code>
   * @return The eventSource.
   */
  java.lang.String getEventSource();
  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>string event_source = 4;</code>
   * @return The bytes for eventSource.
   */
  com.google.protobuf.ByteString
      getEventSourceBytes();

  /**
   * <pre>
   * 事件时间
   * </pre>
   *
   * <code>int64 event_time = 5;</code>
   * @return The eventTime.
   */
  long getEventTime();

  /**
   * <pre>
   * 事件ID
   * </pre>
   *
   * <code>string event_id = 6;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <pre>
   * 事件ID
   * </pre>
   *
   * <code>string event_id = 6;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <pre>
   * 事件版本
   * </pre>
   *
   * <code>string event_version = 7;</code>
   * @return The eventVersion.
   */
  java.lang.String getEventVersion();
  /**
   * <pre>
   * 事件版本
   * </pre>
   *
   * <code>string event_version = 7;</code>
   * @return The bytes for eventVersion.
   */
  com.google.protobuf.ByteString
      getEventVersionBytes();

  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 事件元数据（JSON字符串）
   * </pre>
   *
   * <code>string metadata = 9;</code>
   * @return The metadata.
   */
  java.lang.String getMetadata();
  /**
   * <pre>
   * 事件元数据（JSON字符串）
   * </pre>
   *
   * <code>string metadata = 9;</code>
   * @return The bytes for metadata.
   */
  com.google.protobuf.ByteString
      getMetadataBytes();
}
