// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf type {@code com.acme.im.websocket.EventMessage}
 */
public final class EventMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.EventMessage)
    EventMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventMessage.newBuilder() to construct.
  private EventMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventMessage() {
    eventType_ = "";
    eventName_ = "";
    eventData_ = "";
    eventSource_ = "";
    eventId_ = "";
    eventVersion_ = "";
    tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    metadata_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EventMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EventMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.EventMessage.class, com.acme.im.common.websocket.proto.EventMessage.Builder.class);
  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventType_ = "";
  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>string event_type = 1;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public java.lang.String getEventType() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>string event_type = 1;</code>
   * @return The bytes for eventType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventTypeBytes() {
    java.lang.Object ref = eventType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventName_ = "";
  /**
   * <pre>
   * 事件名称
   * </pre>
   *
   * <code>string event_name = 2;</code>
   * @return The eventName.
   */
  @java.lang.Override
  public java.lang.String getEventName() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件名称
   * </pre>
   *
   * <code>string event_name = 2;</code>
   * @return The bytes for eventName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventNameBytes() {
    java.lang.Object ref = eventName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_DATA_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventData_ = "";
  /**
   * <pre>
   * 事件数据（JSON字符串）
   * </pre>
   *
   * <code>string event_data = 3;</code>
   * @return The eventData.
   */
  @java.lang.Override
  public java.lang.String getEventData() {
    java.lang.Object ref = eventData_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventData_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件数据（JSON字符串）
   * </pre>
   *
   * <code>string event_data = 3;</code>
   * @return The bytes for eventData.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventDataBytes() {
    java.lang.Object ref = eventData_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventData_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_SOURCE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventSource_ = "";
  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>string event_source = 4;</code>
   * @return The eventSource.
   */
  @java.lang.Override
  public java.lang.String getEventSource() {
    java.lang.Object ref = eventSource_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventSource_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>string event_source = 4;</code>
   * @return The bytes for eventSource.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventSourceBytes() {
    java.lang.Object ref = eventSource_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventSource_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_TIME_FIELD_NUMBER = 5;
  private long eventTime_ = 0L;
  /**
   * <pre>
   * 事件时间
   * </pre>
   *
   * <code>int64 event_time = 5;</code>
   * @return The eventTime.
   */
  @java.lang.Override
  public long getEventTime() {
    return eventTime_;
  }

  public static final int EVENT_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <pre>
   * 事件ID
   * </pre>
   *
   * <code>string event_id = 6;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件ID
   * </pre>
   *
   * <code>string event_id = 6;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_VERSION_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventVersion_ = "";
  /**
   * <pre>
   * 事件版本
   * </pre>
   *
   * <code>string event_version = 7;</code>
   * @return The eventVersion.
   */
  @java.lang.Override
  public java.lang.String getEventVersion() {
    java.lang.Object ref = eventVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventVersion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件版本
   * </pre>
   *
   * <code>string event_version = 7;</code>
   * @return The bytes for eventVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventVersionBytes() {
    java.lang.Object ref = eventVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TAGS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList tags_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return A list containing the tags.
   */
  public com.google.protobuf.ProtocolStringList
      getTagsList() {
    return tags_;
  }
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @return The count of tags.
   */
  public int getTagsCount() {
    return tags_.size();
  }
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  public java.lang.String getTags(int index) {
    return tags_.get(index);
  }
  /**
   * <pre>
   * 事件标签
   * </pre>
   *
   * <code>repeated string tags = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  public com.google.protobuf.ByteString
      getTagsBytes(int index) {
    return tags_.getByteString(index);
  }

  public static final int METADATA_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object metadata_ = "";
  /**
   * <pre>
   * 事件元数据（JSON字符串）
   * </pre>
   *
   * <code>string metadata = 9;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public java.lang.String getMetadata() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      metadata_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 事件元数据（JSON字符串）
   * </pre>
   *
   * <code>string metadata = 9;</code>
   * @return The bytes for metadata.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMetadataBytes() {
    java.lang.Object ref = metadata_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      metadata_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventData_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventSource_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, eventSource_);
    }
    if (eventTime_ != 0L) {
      output.writeInt64(5, eventTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventVersion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, eventVersion_);
    }
    for (int i = 0; i < tags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tags_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metadata_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, metadata_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventData_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventData_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventSource_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, eventSource_);
    }
    if (eventTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, eventTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, eventId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(eventVersion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, eventVersion_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tags_.size(); i++) {
        dataSize += computeStringSizeNoTag(tags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagsList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(metadata_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, metadata_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.EventMessage)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.EventMessage other = (com.acme.im.common.websocket.proto.EventMessage) obj;

    if (!getEventType()
        .equals(other.getEventType())) return false;
    if (!getEventName()
        .equals(other.getEventName())) return false;
    if (!getEventData()
        .equals(other.getEventData())) return false;
    if (!getEventSource()
        .equals(other.getEventSource())) return false;
    if (getEventTime()
        != other.getEventTime()) return false;
    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (!getEventVersion()
        .equals(other.getEventVersion())) return false;
    if (!getTagsList()
        .equals(other.getTagsList())) return false;
    if (!getMetadata()
        .equals(other.getMetadata())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getEventType().hashCode();
    hash = (37 * hash) + EVENT_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getEventName().hashCode();
    hash = (37 * hash) + EVENT_DATA_FIELD_NUMBER;
    hash = (53 * hash) + getEventData().hashCode();
    hash = (37 * hash) + EVENT_SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getEventSource().hashCode();
    hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventTime());
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + EVENT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getEventVersion().hashCode();
    if (getTagsCount() > 0) {
      hash = (37 * hash) + TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getTagsList().hashCode();
    }
    hash = (37 * hash) + METADATA_FIELD_NUMBER;
    hash = (53 * hash) + getMetadata().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.EventMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.EventMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.EventMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.EventMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acme.im.websocket.EventMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.EventMessage)
      com.acme.im.common.websocket.proto.EventMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EventMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EventMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.EventMessage.class, com.acme.im.common.websocket.proto.EventMessage.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.EventMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventType_ = "";
      eventName_ = "";
      eventData_ = "";
      eventSource_ = "";
      eventTime_ = 0L;
      eventId_ = "";
      eventVersion_ = "";
      tags_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      metadata_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_EventMessage_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EventMessage getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EventMessage build() {
      com.acme.im.common.websocket.proto.EventMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.EventMessage buildPartial() {
      com.acme.im.common.websocket.proto.EventMessage result = new com.acme.im.common.websocket.proto.EventMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.EventMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventType_ = eventType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.eventName_ = eventName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.eventData_ = eventData_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.eventSource_ = eventSource_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.eventTime_ = eventTime_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.eventVersion_ = eventVersion_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        tags_.makeImmutable();
        result.tags_ = tags_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.metadata_ = metadata_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.EventMessage) {
        return mergeFrom((com.acme.im.common.websocket.proto.EventMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.EventMessage other) {
      if (other == com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance()) return this;
      if (!other.getEventType().isEmpty()) {
        eventType_ = other.eventType_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getEventName().isEmpty()) {
        eventName_ = other.eventName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEventData().isEmpty()) {
        eventData_ = other.eventData_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEventSource().isEmpty()) {
        eventSource_ = other.eventSource_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getEventTime() != 0L) {
        setEventTime(other.getEventTime());
      }
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getEventVersion().isEmpty()) {
        eventVersion_ = other.eventVersion_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.tags_.isEmpty()) {
        if (tags_.isEmpty()) {
          tags_ = other.tags_;
          bitField0_ |= 0x00000080;
        } else {
          ensureTagsIsMutable();
          tags_.addAll(other.tags_);
        }
        onChanged();
      }
      if (!other.getMetadata().isEmpty()) {
        metadata_ = other.metadata_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              eventName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              eventData_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              eventSource_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              eventTime_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              eventVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureTagsIsMutable();
              tags_.add(s);
              break;
            } // case 66
            case 74: {
              metadata_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventType_ = "";
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>string event_type = 1;</code>
     * @return The eventType.
     */
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>string event_type = 1;</code>
     * @return The bytes for eventType.
     */
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>string event_type = 1;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>string event_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      eventType_ = getDefaultInstance().getEventType();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>string event_type = 1;</code>
     * @param value The bytes for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object eventName_ = "";
    /**
     * <pre>
     * 事件名称
     * </pre>
     *
     * <code>string event_name = 2;</code>
     * @return The eventName.
     */
    public java.lang.String getEventName() {
      java.lang.Object ref = eventName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件名称
     * </pre>
     *
     * <code>string event_name = 2;</code>
     * @return The bytes for eventName.
     */
    public com.google.protobuf.ByteString
        getEventNameBytes() {
      java.lang.Object ref = eventName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件名称
     * </pre>
     *
     * <code>string event_name = 2;</code>
     * @param value The eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件名称
     * </pre>
     *
     * <code>string event_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventName() {
      eventName_ = getDefaultInstance().getEventName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件名称
     * </pre>
     *
     * <code>string event_name = 2;</code>
     * @param value The bytes for eventName to set.
     * @return This builder for chaining.
     */
    public Builder setEventNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object eventData_ = "";
    /**
     * <pre>
     * 事件数据（JSON字符串）
     * </pre>
     *
     * <code>string event_data = 3;</code>
     * @return The eventData.
     */
    public java.lang.String getEventData() {
      java.lang.Object ref = eventData_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventData_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件数据（JSON字符串）
     * </pre>
     *
     * <code>string event_data = 3;</code>
     * @return The bytes for eventData.
     */
    public com.google.protobuf.ByteString
        getEventDataBytes() {
      java.lang.Object ref = eventData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件数据（JSON字符串）
     * </pre>
     *
     * <code>string event_data = 3;</code>
     * @param value The eventData to set.
     * @return This builder for chaining.
     */
    public Builder setEventData(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventData_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件数据（JSON字符串）
     * </pre>
     *
     * <code>string event_data = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventData() {
      eventData_ = getDefaultInstance().getEventData();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件数据（JSON字符串）
     * </pre>
     *
     * <code>string event_data = 3;</code>
     * @param value The bytes for eventData to set.
     * @return This builder for chaining.
     */
    public Builder setEventDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventData_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object eventSource_ = "";
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>string event_source = 4;</code>
     * @return The eventSource.
     */
    public java.lang.String getEventSource() {
      java.lang.Object ref = eventSource_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventSource_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>string event_source = 4;</code>
     * @return The bytes for eventSource.
     */
    public com.google.protobuf.ByteString
        getEventSourceBytes() {
      java.lang.Object ref = eventSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>string event_source = 4;</code>
     * @param value The eventSource to set.
     * @return This builder for chaining.
     */
    public Builder setEventSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventSource_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>string event_source = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventSource() {
      eventSource_ = getDefaultInstance().getEventSource();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>string event_source = 4;</code>
     * @param value The bytes for eventSource to set.
     * @return This builder for chaining.
     */
    public Builder setEventSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventSource_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long eventTime_ ;
    /**
     * <pre>
     * 事件时间
     * </pre>
     *
     * <code>int64 event_time = 5;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public long getEventTime() {
      return eventTime_;
    }
    /**
     * <pre>
     * 事件时间
     * </pre>
     *
     * <code>int64 event_time = 5;</code>
     * @param value The eventTime to set.
     * @return This builder for chaining.
     */
    public Builder setEventTime(long value) {

      eventTime_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件时间
     * </pre>
     *
     * <code>int64 event_time = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTime() {
      bitField0_ = (bitField0_ & ~0x00000010);
      eventTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object eventId_ = "";
    /**
     * <pre>
     * 事件ID
     * </pre>
     *
     * <code>string event_id = 6;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件ID
     * </pre>
     *
     * <code>string event_id = 6;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件ID
     * </pre>
     *
     * <code>string event_id = 6;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件ID
     * </pre>
     *
     * <code>string event_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件ID
     * </pre>
     *
     * <code>string event_id = 6;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object eventVersion_ = "";
    /**
     * <pre>
     * 事件版本
     * </pre>
     *
     * <code>string event_version = 7;</code>
     * @return The eventVersion.
     */
    public java.lang.String getEventVersion() {
      java.lang.Object ref = eventVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件版本
     * </pre>
     *
     * <code>string event_version = 7;</code>
     * @return The bytes for eventVersion.
     */
    public com.google.protobuf.ByteString
        getEventVersionBytes() {
      java.lang.Object ref = eventVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件版本
     * </pre>
     *
     * <code>string event_version = 7;</code>
     * @param value The eventVersion to set.
     * @return This builder for chaining.
     */
    public Builder setEventVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      eventVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件版本
     * </pre>
     *
     * <code>string event_version = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventVersion() {
      eventVersion_ = getDefaultInstance().getEventVersion();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件版本
     * </pre>
     *
     * <code>string event_version = 7;</code>
     * @param value The bytes for eventVersion to set.
     * @return This builder for chaining.
     */
    public Builder setEventVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      eventVersion_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTagsIsMutable() {
      if (!tags_.isModifiable()) {
        tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
      }
      bitField0_ |= 0x00000080;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return A list containing the tags.
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      tags_.makeImmutable();
      return tags_;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return The count of tags.
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index of the element to return.
     * @return The tags at the given index.
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the tags at the given index.
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param index The index to set the value at.
     * @param value The tags to set.
     * @return This builder for chaining.
     */
    public Builder setTags(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.set(index, value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param value The tags to add.
     * @return This builder for chaining.
     */
    public Builder addTags(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param values The tags to add.
     * @return This builder for chaining.
     */
    public Builder addAllTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tags_);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTags() {
      tags_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件标签
     * </pre>
     *
     * <code>repeated string tags = 8;</code>
     * @param value The bytes of the tags to add.
     * @return This builder for chaining.
     */
    public Builder addTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureTagsIsMutable();
      tags_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object metadata_ = "";
    /**
     * <pre>
     * 事件元数据（JSON字符串）
     * </pre>
     *
     * <code>string metadata = 9;</code>
     * @return The metadata.
     */
    public java.lang.String getMetadata() {
      java.lang.Object ref = metadata_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        metadata_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 事件元数据（JSON字符串）
     * </pre>
     *
     * <code>string metadata = 9;</code>
     * @return The bytes for metadata.
     */
    public com.google.protobuf.ByteString
        getMetadataBytes() {
      java.lang.Object ref = metadata_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        metadata_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 事件元数据（JSON字符串）
     * </pre>
     *
     * <code>string metadata = 9;</code>
     * @param value The metadata to set.
     * @return This builder for chaining.
     */
    public Builder setMetadata(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      metadata_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件元数据（JSON字符串）
     * </pre>
     *
     * <code>string metadata = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetadata() {
      metadata_ = getDefaultInstance().getMetadata();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件元数据（JSON字符串）
     * </pre>
     *
     * <code>string metadata = 9;</code>
     * @param value The bytes for metadata to set.
     * @return This builder for chaining.
     */
    public Builder setMetadataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      metadata_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.EventMessage)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.EventMessage)
  private static final com.acme.im.common.websocket.proto.EventMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.EventMessage();
  }

  public static com.acme.im.common.websocket.proto.EventMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventMessage>
      PARSER = new com.google.protobuf.AbstractParser<EventMessage>() {
    @java.lang.Override
    public EventMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.EventMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

