// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf type {@code com.acme.im.websocket.ForwardInfo}
 */
public final class ForwardInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.ForwardInfo)
    ForwardInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ForwardInfo.newBuilder() to construct.
  private ForwardInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ForwardInfo() {
    originalConversationId_ = "";
    originalSenderId_ = "";
    forwardReason_ = "";
    forwardChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ForwardInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ForwardInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ForwardInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.ForwardInfo.class, com.acme.im.common.websocket.proto.ForwardInfo.Builder.class);
  }

  public static final int ORIGINAL_CONVERSATION_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalConversationId_ = "";
  /**
   * <pre>
   * 原始会话ID
   * </pre>
   *
   * <code>string original_conversation_id = 1;</code>
   * @return The originalConversationId.
   */
  @java.lang.Override
  public java.lang.String getOriginalConversationId() {
    java.lang.Object ref = originalConversationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalConversationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始会话ID
   * </pre>
   *
   * <code>string original_conversation_id = 1;</code>
   * @return The bytes for originalConversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalConversationIdBytes() {
    java.lang.Object ref = originalConversationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalConversationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_SENDER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object originalSenderId_ = "";
  /**
   * <pre>
   * 原始发送者ID
   * </pre>
   *
   * <code>string original_sender_id = 2;</code>
   * @return The originalSenderId.
   */
  @java.lang.Override
  public java.lang.String getOriginalSenderId() {
    java.lang.Object ref = originalSenderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalSenderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始发送者ID
   * </pre>
   *
   * <code>string original_sender_id = 2;</code>
   * @return The bytes for originalSenderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalSenderIdBytes() {
    java.lang.Object ref = originalSenderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalSenderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORWARD_REASON_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object forwardReason_ = "";
  /**
   * <pre>
   * 转发原因
   * </pre>
   *
   * <code>string forward_reason = 3;</code>
   * @return The forwardReason.
   */
  @java.lang.Override
  public java.lang.String getForwardReason() {
    java.lang.Object ref = forwardReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      forwardReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 转发原因
   * </pre>
   *
   * <code>string forward_reason = 3;</code>
   * @return The bytes for forwardReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getForwardReasonBytes() {
    java.lang.Object ref = forwardReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      forwardReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FORWARD_CHAIN_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList forwardChain_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @return A list containing the forwardChain.
   */
  public com.google.protobuf.ProtocolStringList
      getForwardChainList() {
    return forwardChain_;
  }
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @return The count of forwardChain.
   */
  public int getForwardChainCount() {
    return forwardChain_.size();
  }
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @param index The index of the element to return.
   * @return The forwardChain at the given index.
   */
  public java.lang.String getForwardChain(int index) {
    return forwardChain_.get(index);
  }
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the forwardChain at the given index.
   */
  public com.google.protobuf.ByteString
      getForwardChainBytes(int index) {
    return forwardChain_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalConversationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, originalConversationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalSenderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, originalSenderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forwardReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, forwardReason_);
    }
    for (int i = 0; i < forwardChain_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, forwardChain_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalConversationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, originalConversationId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalSenderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, originalSenderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forwardReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, forwardReason_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < forwardChain_.size(); i++) {
        dataSize += computeStringSizeNoTag(forwardChain_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getForwardChainList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.ForwardInfo)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.ForwardInfo other = (com.acme.im.common.websocket.proto.ForwardInfo) obj;

    if (!getOriginalConversationId()
        .equals(other.getOriginalConversationId())) return false;
    if (!getOriginalSenderId()
        .equals(other.getOriginalSenderId())) return false;
    if (!getForwardReason()
        .equals(other.getForwardReason())) return false;
    if (!getForwardChainList()
        .equals(other.getForwardChainList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ORIGINAL_CONVERSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalConversationId().hashCode();
    hash = (37 * hash) + ORIGINAL_SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalSenderId().hashCode();
    hash = (37 * hash) + FORWARD_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getForwardReason().hashCode();
    if (getForwardChainCount() > 0) {
      hash = (37 * hash) + FORWARD_CHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getForwardChainList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.ForwardInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.ForwardInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.ForwardInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.ForwardInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acme.im.websocket.ForwardInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.ForwardInfo)
      com.acme.im.common.websocket.proto.ForwardInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ForwardInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ForwardInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.ForwardInfo.class, com.acme.im.common.websocket.proto.ForwardInfo.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.ForwardInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      originalConversationId_ = "";
      originalSenderId_ = "";
      forwardReason_ = "";
      forwardChain_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_ForwardInfo_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ForwardInfo getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ForwardInfo build() {
      com.acme.im.common.websocket.proto.ForwardInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.ForwardInfo buildPartial() {
      com.acme.im.common.websocket.proto.ForwardInfo result = new com.acme.im.common.websocket.proto.ForwardInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.ForwardInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.originalConversationId_ = originalConversationId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.originalSenderId_ = originalSenderId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.forwardReason_ = forwardReason_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        forwardChain_.makeImmutable();
        result.forwardChain_ = forwardChain_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.ForwardInfo) {
        return mergeFrom((com.acme.im.common.websocket.proto.ForwardInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.ForwardInfo other) {
      if (other == com.acme.im.common.websocket.proto.ForwardInfo.getDefaultInstance()) return this;
      if (!other.getOriginalConversationId().isEmpty()) {
        originalConversationId_ = other.originalConversationId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getOriginalSenderId().isEmpty()) {
        originalSenderId_ = other.originalSenderId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getForwardReason().isEmpty()) {
        forwardReason_ = other.forwardReason_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.forwardChain_.isEmpty()) {
        if (forwardChain_.isEmpty()) {
          forwardChain_ = other.forwardChain_;
          bitField0_ |= 0x00000008;
        } else {
          ensureForwardChainIsMutable();
          forwardChain_.addAll(other.forwardChain_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              originalConversationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              originalSenderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              forwardReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureForwardChainIsMutable();
              forwardChain_.add(s);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object originalConversationId_ = "";
    /**
     * <pre>
     * 原始会话ID
     * </pre>
     *
     * <code>string original_conversation_id = 1;</code>
     * @return The originalConversationId.
     */
    public java.lang.String getOriginalConversationId() {
      java.lang.Object ref = originalConversationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalConversationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始会话ID
     * </pre>
     *
     * <code>string original_conversation_id = 1;</code>
     * @return The bytes for originalConversationId.
     */
    public com.google.protobuf.ByteString
        getOriginalConversationIdBytes() {
      java.lang.Object ref = originalConversationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalConversationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始会话ID
     * </pre>
     *
     * <code>string original_conversation_id = 1;</code>
     * @param value The originalConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalConversationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalConversationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始会话ID
     * </pre>
     *
     * <code>string original_conversation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalConversationId() {
      originalConversationId_ = getDefaultInstance().getOriginalConversationId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始会话ID
     * </pre>
     *
     * <code>string original_conversation_id = 1;</code>
     * @param value The bytes for originalConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalConversationId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object originalSenderId_ = "";
    /**
     * <pre>
     * 原始发送者ID
     * </pre>
     *
     * <code>string original_sender_id = 2;</code>
     * @return The originalSenderId.
     */
    public java.lang.String getOriginalSenderId() {
      java.lang.Object ref = originalSenderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalSenderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始发送者ID
     * </pre>
     *
     * <code>string original_sender_id = 2;</code>
     * @return The bytes for originalSenderId.
     */
    public com.google.protobuf.ByteString
        getOriginalSenderIdBytes() {
      java.lang.Object ref = originalSenderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalSenderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始发送者ID
     * </pre>
     *
     * <code>string original_sender_id = 2;</code>
     * @param value The originalSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalSenderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      originalSenderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始发送者ID
     * </pre>
     *
     * <code>string original_sender_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalSenderId() {
      originalSenderId_ = getDefaultInstance().getOriginalSenderId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始发送者ID
     * </pre>
     *
     * <code>string original_sender_id = 2;</code>
     * @param value The bytes for originalSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      originalSenderId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object forwardReason_ = "";
    /**
     * <pre>
     * 转发原因
     * </pre>
     *
     * <code>string forward_reason = 3;</code>
     * @return The forwardReason.
     */
    public java.lang.String getForwardReason() {
      java.lang.Object ref = forwardReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        forwardReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 转发原因
     * </pre>
     *
     * <code>string forward_reason = 3;</code>
     * @return The bytes for forwardReason.
     */
    public com.google.protobuf.ByteString
        getForwardReasonBytes() {
      java.lang.Object ref = forwardReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        forwardReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 转发原因
     * </pre>
     *
     * <code>string forward_reason = 3;</code>
     * @param value The forwardReason to set.
     * @return This builder for chaining.
     */
    public Builder setForwardReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      forwardReason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发原因
     * </pre>
     *
     * <code>string forward_reason = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearForwardReason() {
      forwardReason_ = getDefaultInstance().getForwardReason();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发原因
     * </pre>
     *
     * <code>string forward_reason = 3;</code>
     * @param value The bytes for forwardReason to set.
     * @return This builder for chaining.
     */
    public Builder setForwardReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      forwardReason_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList forwardChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureForwardChainIsMutable() {
      if (!forwardChain_.isModifiable()) {
        forwardChain_ = new com.google.protobuf.LazyStringArrayList(forwardChain_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @return A list containing the forwardChain.
     */
    public com.google.protobuf.ProtocolStringList
        getForwardChainList() {
      forwardChain_.makeImmutable();
      return forwardChain_;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @return The count of forwardChain.
     */
    public int getForwardChainCount() {
      return forwardChain_.size();
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param index The index of the element to return.
     * @return The forwardChain at the given index.
     */
    public java.lang.String getForwardChain(int index) {
      return forwardChain_.get(index);
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the forwardChain at the given index.
     */
    public com.google.protobuf.ByteString
        getForwardChainBytes(int index) {
      return forwardChain_.getByteString(index);
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param index The index to set the value at.
     * @param value The forwardChain to set.
     * @return This builder for chaining.
     */
    public Builder setForwardChain(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureForwardChainIsMutable();
      forwardChain_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param value The forwardChain to add.
     * @return This builder for chaining.
     */
    public Builder addForwardChain(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureForwardChainIsMutable();
      forwardChain_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param values The forwardChain to add.
     * @return This builder for chaining.
     */
    public Builder addAllForwardChain(
        java.lang.Iterable<java.lang.String> values) {
      ensureForwardChainIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, forwardChain_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearForwardChain() {
      forwardChain_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 转发链（最多支持5级转发）
     * </pre>
     *
     * <code>repeated string forward_chain = 4;</code>
     * @param value The bytes of the forwardChain to add.
     * @return This builder for chaining.
     */
    public Builder addForwardChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureForwardChainIsMutable();
      forwardChain_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.ForwardInfo)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.ForwardInfo)
  private static final com.acme.im.common.websocket.proto.ForwardInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.ForwardInfo();
  }

  public static com.acme.im.common.websocket.proto.ForwardInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ForwardInfo>
      PARSER = new com.google.protobuf.AbstractParser<ForwardInfo>() {
    @java.lang.Override
    public ForwardInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ForwardInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ForwardInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.ForwardInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

