// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface ForwardInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.ForwardInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 原始会话ID
   * </pre>
   *
   * <code>string original_conversation_id = 1;</code>
   * @return The originalConversationId.
   */
  java.lang.String getOriginalConversationId();
  /**
   * <pre>
   * 原始会话ID
   * </pre>
   *
   * <code>string original_conversation_id = 1;</code>
   * @return The bytes for originalConversationId.
   */
  com.google.protobuf.ByteString
      getOriginalConversationIdBytes();

  /**
   * <pre>
   * 原始发送者ID
   * </pre>
   *
   * <code>string original_sender_id = 2;</code>
   * @return The originalSenderId.
   */
  java.lang.String getOriginalSenderId();
  /**
   * <pre>
   * 原始发送者ID
   * </pre>
   *
   * <code>string original_sender_id = 2;</code>
   * @return The bytes for originalSenderId.
   */
  com.google.protobuf.ByteString
      getOriginalSenderIdBytes();

  /**
   * <pre>
   * 转发原因
   * </pre>
   *
   * <code>string forward_reason = 3;</code>
   * @return The forwardReason.
   */
  java.lang.String getForwardReason();
  /**
   * <pre>
   * 转发原因
   * </pre>
   *
   * <code>string forward_reason = 3;</code>
   * @return The bytes for forwardReason.
   */
  com.google.protobuf.ByteString
      getForwardReasonBytes();

  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @return A list containing the forwardChain.
   */
  java.util.List<java.lang.String>
      getForwardChainList();
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @return The count of forwardChain.
   */
  int getForwardChainCount();
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @param index The index of the element to return.
   * @return The forwardChain at the given index.
   */
  java.lang.String getForwardChain(int index);
  /**
   * <pre>
   * 转发链（最多支持5级转发）
   * </pre>
   *
   * <code>repeated string forward_chain = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the forwardChain at the given index.
   */
  com.google.protobuf.ByteString
      getForwardChainBytes(int index);
}
