// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf enum {@code com.acme.im.websocket.MessageStatus}
 */
public enum MessageStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 已删除
   * </pre>
   *
   * <code>MESSAGE_DELETED = 0;</code>
   */
  MESSAGE_DELETED(0),
  /**
   * <pre>
   * 正常
   * </pre>
   *
   * <code>MESSAGE_NORMAL = 1;</code>
   */
  MESSAGE_NORMAL(1),
  /**
   * <pre>
   * 审核中
   * </pre>
   *
   * <code>MESSAGE_PENDING = 2;</code>
   */
  MESSAGE_PENDING(2),
  /**
   * <pre>
   * 已拒绝
   * </pre>
   *
   * <code>MESSAGE_REJECTED = 3;</code>
   */
  MESSAGE_REJECTED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 已删除
   * </pre>
   *
   * <code>MESSAGE_DELETED = 0;</code>
   */
  public static final int MESSAGE_DELETED_VALUE = 0;
  /**
   * <pre>
   * 正常
   * </pre>
   *
   * <code>MESSAGE_NORMAL = 1;</code>
   */
  public static final int MESSAGE_NORMAL_VALUE = 1;
  /**
   * <pre>
   * 审核中
   * </pre>
   *
   * <code>MESSAGE_PENDING = 2;</code>
   */
  public static final int MESSAGE_PENDING_VALUE = 2;
  /**
   * <pre>
   * 已拒绝
   * </pre>
   *
   * <code>MESSAGE_REJECTED = 3;</code>
   */
  public static final int MESSAGE_REJECTED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageStatus forNumber(int value) {
    switch (value) {
      case 0: return MESSAGE_DELETED;
      case 1: return MESSAGE_NORMAL;
      case 2: return MESSAGE_PENDING;
      case 3: return MESSAGE_REJECTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageStatus>() {
          public MessageStatus findValueByNumber(int number) {
            return MessageStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final MessageStatus[] VALUES = values();

  public static MessageStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.acme.im.websocket.MessageStatus)
}

