// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface NotificationMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.NotificationMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 通知标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * 通知标题
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * 通知内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 通知内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 通知类型
   * </pre>
   *
   * <code>string notification_type = 3;</code>
   * @return The notificationType.
   */
  java.lang.String getNotificationType();
  /**
   * <pre>
   * 通知类型
   * </pre>
   *
   * <code>string notification_type = 3;</code>
   * @return The bytes for notificationType.
   */
  com.google.protobuf.ByteString
      getNotificationTypeBytes();

  /**
   * <pre>
   * 通知级别：INFO、WARNING、ERROR、CRITICAL
   * </pre>
   *
   * <code>string level = 4;</code>
   * @return The level.
   */
  java.lang.String getLevel();
  /**
   * <pre>
   * 通知级别：INFO、WARNING、ERROR、CRITICAL
   * </pre>
   *
   * <code>string level = 4;</code>
   * @return The bytes for level.
   */
  com.google.protobuf.ByteString
      getLevelBytes();

  /**
   * <pre>
   * 通知分类
   * </pre>
   *
   * <code>string category = 5;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * 通知分类
   * </pre>
   *
   * <code>string category = 5;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * 通知动作
   * </pre>
   *
   * <code>string action = 6;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * 通知动作
   * </pre>
   *
   * <code>string action = 6;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * 动作URL
   * </pre>
   *
   * <code>string action_url = 7;</code>
   * @return The actionUrl.
   */
  java.lang.String getActionUrl();
  /**
   * <pre>
   * 动作URL
   * </pre>
   *
   * <code>string action_url = 7;</code>
   * @return The bytes for actionUrl.
   */
  com.google.protobuf.ByteString
      getActionUrlBytes();

  /**
   * <pre>
   * 通知图标
   * </pre>
   *
   * <code>string icon = 8;</code>
   * @return The icon.
   */
  java.lang.String getIcon();
  /**
   * <pre>
   * 通知图标
   * </pre>
   *
   * <code>string icon = 8;</code>
   * @return The bytes for icon.
   */
  com.google.protobuf.ByteString
      getIconBytes();

  /**
   * <pre>
   * 通知图片
   * </pre>
   *
   * <code>string image = 9;</code>
   * @return The image.
   */
  java.lang.String getImage();
  /**
   * <pre>
   * 通知图片
   * </pre>
   *
   * <code>string image = 9;</code>
   * @return The bytes for image.
   */
  com.google.protobuf.ByteString
      getImageBytes();

  /**
   * <pre>
   * 通知标签
   * </pre>
   *
   * <code>repeated string tags = 10;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * 通知标签
   * </pre>
   *
   * <code>repeated string tags = 10;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * 通知标签
   * </pre>
   *
   * <code>repeated string tags = 10;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * 通知标签
   * </pre>
   *
   * <code>repeated string tags = 10;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 过期时间
   * </pre>
   *
   * <code>int64 expires_at = 11;</code>
   * @return The expiresAt.
   */
  long getExpiresAt();
}
