// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * Protobuf type {@code com.acme.im.websocket.QuoteInfo}
 */
public final class QuoteInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.QuoteInfo)
    QuoteInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QuoteInfo.newBuilder() to construct.
  private QuoteInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QuoteInfo() {
    quotedMessageId_ = "";
    quotedContent_ = "";
    quotedSenderId_ = "";
    quotedContentType_ = "";
    quoteReason_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QuoteInfo();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_QuoteInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_QuoteInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.QuoteInfo.class, com.acme.im.common.websocket.proto.QuoteInfo.Builder.class);
  }

  public static final int QUOTED_MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quotedMessageId_ = "";
  /**
   * <pre>
   * 被引用的消息ID
   * </pre>
   *
   * <code>string quoted_message_id = 1;</code>
   * @return The quotedMessageId.
   */
  @java.lang.Override
  public java.lang.String getQuotedMessageId() {
    java.lang.Object ref = quotedMessageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quotedMessageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 被引用的消息ID
   * </pre>
   *
   * <code>string quoted_message_id = 1;</code>
   * @return The bytes for quotedMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuotedMessageIdBytes() {
    java.lang.Object ref = quotedMessageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quotedMessageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTED_CONTENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quotedContent_ = "";
  /**
   * <pre>
   * 被引用的消息内容（截取）
   * </pre>
   *
   * <code>string quoted_content = 2;</code>
   * @return The quotedContent.
   */
  @java.lang.Override
  public java.lang.String getQuotedContent() {
    java.lang.Object ref = quotedContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quotedContent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 被引用的消息内容（截取）
   * </pre>
   *
   * <code>string quoted_content = 2;</code>
   * @return The bytes for quotedContent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuotedContentBytes() {
    java.lang.Object ref = quotedContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quotedContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTED_SENDER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quotedSenderId_ = "";
  /**
   * <pre>
   * 被引用消息的发送者ID
   * </pre>
   *
   * <code>string quoted_sender_id = 3;</code>
   * @return The quotedSenderId.
   */
  @java.lang.Override
  public java.lang.String getQuotedSenderId() {
    java.lang.Object ref = quotedSenderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quotedSenderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 被引用消息的发送者ID
   * </pre>
   *
   * <code>string quoted_sender_id = 3;</code>
   * @return The bytes for quotedSenderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuotedSenderIdBytes() {
    java.lang.Object ref = quotedSenderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quotedSenderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTED_CONTENT_TYPE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quotedContentType_ = "";
  /**
   * <pre>
   * 被引用消息的内容类型
   * </pre>
   *
   * <code>string quoted_content_type = 4;</code>
   * @return The quotedContentType.
   */
  @java.lang.Override
  public java.lang.String getQuotedContentType() {
    java.lang.Object ref = quotedContentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quotedContentType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 被引用消息的内容类型
   * </pre>
   *
   * <code>string quoted_content_type = 4;</code>
   * @return The bytes for quotedContentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuotedContentTypeBytes() {
    java.lang.Object ref = quotedContentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quotedContentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUOTE_REASON_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object quoteReason_ = "";
  /**
   * <pre>
   * 引用原因
   * </pre>
   *
   * <code>string quote_reason = 5;</code>
   * @return The quoteReason.
   */
  @java.lang.Override
  public java.lang.String getQuoteReason() {
    java.lang.Object ref = quoteReason_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      quoteReason_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 引用原因
   * </pre>
   *
   * <code>string quote_reason = 5;</code>
   * @return The bytes for quoteReason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQuoteReasonBytes() {
    java.lang.Object ref = quoteReason_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      quoteReason_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedMessageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, quotedMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedContent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, quotedContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedSenderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, quotedSenderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedContentType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, quotedContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quoteReason_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, quoteReason_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedMessageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, quotedMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedContent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, quotedContent_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedSenderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, quotedSenderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quotedContentType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, quotedContentType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(quoteReason_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, quoteReason_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.QuoteInfo)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.QuoteInfo other = (com.acme.im.common.websocket.proto.QuoteInfo) obj;

    if (!getQuotedMessageId()
        .equals(other.getQuotedMessageId())) return false;
    if (!getQuotedContent()
        .equals(other.getQuotedContent())) return false;
    if (!getQuotedSenderId()
        .equals(other.getQuotedSenderId())) return false;
    if (!getQuotedContentType()
        .equals(other.getQuotedContentType())) return false;
    if (!getQuoteReason()
        .equals(other.getQuoteReason())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + QUOTED_MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getQuotedMessageId().hashCode();
    hash = (37 * hash) + QUOTED_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getQuotedContent().hashCode();
    hash = (37 * hash) + QUOTED_SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getQuotedSenderId().hashCode();
    hash = (37 * hash) + QUOTED_CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getQuotedContentType().hashCode();
    hash = (37 * hash) + QUOTE_REASON_FIELD_NUMBER;
    hash = (53 * hash) + getQuoteReason().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.QuoteInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.QuoteInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.QuoteInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.QuoteInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.acme.im.websocket.QuoteInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.QuoteInfo)
      com.acme.im.common.websocket.proto.QuoteInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_QuoteInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_QuoteInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.QuoteInfo.class, com.acme.im.common.websocket.proto.QuoteInfo.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.QuoteInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      quotedMessageId_ = "";
      quotedContent_ = "";
      quotedSenderId_ = "";
      quotedContentType_ = "";
      quoteReason_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_QuoteInfo_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.QuoteInfo getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.QuoteInfo build() {
      com.acme.im.common.websocket.proto.QuoteInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.QuoteInfo buildPartial() {
      com.acme.im.common.websocket.proto.QuoteInfo result = new com.acme.im.common.websocket.proto.QuoteInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.QuoteInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.quotedMessageId_ = quotedMessageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.quotedContent_ = quotedContent_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.quotedSenderId_ = quotedSenderId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.quotedContentType_ = quotedContentType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.quoteReason_ = quoteReason_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.QuoteInfo) {
        return mergeFrom((com.acme.im.common.websocket.proto.QuoteInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.QuoteInfo other) {
      if (other == com.acme.im.common.websocket.proto.QuoteInfo.getDefaultInstance()) return this;
      if (!other.getQuotedMessageId().isEmpty()) {
        quotedMessageId_ = other.quotedMessageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getQuotedContent().isEmpty()) {
        quotedContent_ = other.quotedContent_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getQuotedSenderId().isEmpty()) {
        quotedSenderId_ = other.quotedSenderId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getQuotedContentType().isEmpty()) {
        quotedContentType_ = other.quotedContentType_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getQuoteReason().isEmpty()) {
        quoteReason_ = other.quoteReason_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              quotedMessageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              quotedContent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              quotedSenderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              quotedContentType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              quoteReason_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object quotedMessageId_ = "";
    /**
     * <pre>
     * 被引用的消息ID
     * </pre>
     *
     * <code>string quoted_message_id = 1;</code>
     * @return The quotedMessageId.
     */
    public java.lang.String getQuotedMessageId() {
      java.lang.Object ref = quotedMessageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quotedMessageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 被引用的消息ID
     * </pre>
     *
     * <code>string quoted_message_id = 1;</code>
     * @return The bytes for quotedMessageId.
     */
    public com.google.protobuf.ByteString
        getQuotedMessageIdBytes() {
      java.lang.Object ref = quotedMessageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quotedMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 被引用的消息ID
     * </pre>
     *
     * <code>string quoted_message_id = 1;</code>
     * @param value The quotedMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quotedMessageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用的消息ID
     * </pre>
     *
     * <code>string quoted_message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotedMessageId() {
      quotedMessageId_ = getDefaultInstance().getQuotedMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用的消息ID
     * </pre>
     *
     * <code>string quoted_message_id = 1;</code>
     * @param value The bytes for quotedMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quotedMessageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object quotedContent_ = "";
    /**
     * <pre>
     * 被引用的消息内容（截取）
     * </pre>
     *
     * <code>string quoted_content = 2;</code>
     * @return The quotedContent.
     */
    public java.lang.String getQuotedContent() {
      java.lang.Object ref = quotedContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quotedContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 被引用的消息内容（截取）
     * </pre>
     *
     * <code>string quoted_content = 2;</code>
     * @return The bytes for quotedContent.
     */
    public com.google.protobuf.ByteString
        getQuotedContentBytes() {
      java.lang.Object ref = quotedContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quotedContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 被引用的消息内容（截取）
     * </pre>
     *
     * <code>string quoted_content = 2;</code>
     * @param value The quotedContent to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedContent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quotedContent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用的消息内容（截取）
     * </pre>
     *
     * <code>string quoted_content = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotedContent() {
      quotedContent_ = getDefaultInstance().getQuotedContent();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用的消息内容（截取）
     * </pre>
     *
     * <code>string quoted_content = 2;</code>
     * @param value The bytes for quotedContent to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quotedContent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object quotedSenderId_ = "";
    /**
     * <pre>
     * 被引用消息的发送者ID
     * </pre>
     *
     * <code>string quoted_sender_id = 3;</code>
     * @return The quotedSenderId.
     */
    public java.lang.String getQuotedSenderId() {
      java.lang.Object ref = quotedSenderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quotedSenderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 被引用消息的发送者ID
     * </pre>
     *
     * <code>string quoted_sender_id = 3;</code>
     * @return The bytes for quotedSenderId.
     */
    public com.google.protobuf.ByteString
        getQuotedSenderIdBytes() {
      java.lang.Object ref = quotedSenderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quotedSenderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 被引用消息的发送者ID
     * </pre>
     *
     * <code>string quoted_sender_id = 3;</code>
     * @param value The quotedSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedSenderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quotedSenderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用消息的发送者ID
     * </pre>
     *
     * <code>string quoted_sender_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotedSenderId() {
      quotedSenderId_ = getDefaultInstance().getQuotedSenderId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用消息的发送者ID
     * </pre>
     *
     * <code>string quoted_sender_id = 3;</code>
     * @param value The bytes for quotedSenderId to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quotedSenderId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object quotedContentType_ = "";
    /**
     * <pre>
     * 被引用消息的内容类型
     * </pre>
     *
     * <code>string quoted_content_type = 4;</code>
     * @return The quotedContentType.
     */
    public java.lang.String getQuotedContentType() {
      java.lang.Object ref = quotedContentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quotedContentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 被引用消息的内容类型
     * </pre>
     *
     * <code>string quoted_content_type = 4;</code>
     * @return The bytes for quotedContentType.
     */
    public com.google.protobuf.ByteString
        getQuotedContentTypeBytes() {
      java.lang.Object ref = quotedContentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quotedContentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 被引用消息的内容类型
     * </pre>
     *
     * <code>string quoted_content_type = 4;</code>
     * @param value The quotedContentType to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedContentType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quotedContentType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用消息的内容类型
     * </pre>
     *
     * <code>string quoted_content_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuotedContentType() {
      quotedContentType_ = getDefaultInstance().getQuotedContentType();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 被引用消息的内容类型
     * </pre>
     *
     * <code>string quoted_content_type = 4;</code>
     * @param value The bytes for quotedContentType to set.
     * @return This builder for chaining.
     */
    public Builder setQuotedContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quotedContentType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object quoteReason_ = "";
    /**
     * <pre>
     * 引用原因
     * </pre>
     *
     * <code>string quote_reason = 5;</code>
     * @return The quoteReason.
     */
    public java.lang.String getQuoteReason() {
      java.lang.Object ref = quoteReason_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        quoteReason_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 引用原因
     * </pre>
     *
     * <code>string quote_reason = 5;</code>
     * @return The bytes for quoteReason.
     */
    public com.google.protobuf.ByteString
        getQuoteReasonBytes() {
      java.lang.Object ref = quoteReason_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        quoteReason_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 引用原因
     * </pre>
     *
     * <code>string quote_reason = 5;</code>
     * @param value The quoteReason to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteReason(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      quoteReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引用原因
     * </pre>
     *
     * <code>string quote_reason = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuoteReason() {
      quoteReason_ = getDefaultInstance().getQuoteReason();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 引用原因
     * </pre>
     *
     * <code>string quote_reason = 5;</code>
     * @param value The bytes for quoteReason to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteReasonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      quoteReason_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.QuoteInfo)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.QuoteInfo)
  private static final com.acme.im.common.websocket.proto.QuoteInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.QuoteInfo();
  }

  public static com.acme.im.common.websocket.proto.QuoteInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QuoteInfo>
      PARSER = new com.google.protobuf.AbstractParser<QuoteInfo>() {
    @java.lang.Override
    public QuoteInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QuoteInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QuoteInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.QuoteInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

