// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface QuoteInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.QuoteInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 被引用的消息ID
   * </pre>
   *
   * <code>string quoted_message_id = 1;</code>
   * @return The quotedMessageId.
   */
  java.lang.String getQuotedMessageId();
  /**
   * <pre>
   * 被引用的消息ID
   * </pre>
   *
   * <code>string quoted_message_id = 1;</code>
   * @return The bytes for quotedMessageId.
   */
  com.google.protobuf.ByteString
      getQuotedMessageIdBytes();

  /**
   * <pre>
   * 被引用的消息内容（截取）
   * </pre>
   *
   * <code>string quoted_content = 2;</code>
   * @return The quotedContent.
   */
  java.lang.String getQuotedContent();
  /**
   * <pre>
   * 被引用的消息内容（截取）
   * </pre>
   *
   * <code>string quoted_content = 2;</code>
   * @return The bytes for quotedContent.
   */
  com.google.protobuf.ByteString
      getQuotedContentBytes();

  /**
   * <pre>
   * 被引用消息的发送者ID
   * </pre>
   *
   * <code>string quoted_sender_id = 3;</code>
   * @return The quotedSenderId.
   */
  java.lang.String getQuotedSenderId();
  /**
   * <pre>
   * 被引用消息的发送者ID
   * </pre>
   *
   * <code>string quoted_sender_id = 3;</code>
   * @return The bytes for quotedSenderId.
   */
  com.google.protobuf.ByteString
      getQuotedSenderIdBytes();

  /**
   * <pre>
   * 被引用消息的内容类型
   * </pre>
   *
   * <code>string quoted_content_type = 4;</code>
   * @return The quotedContentType.
   */
  java.lang.String getQuotedContentType();
  /**
   * <pre>
   * 被引用消息的内容类型
   * </pre>
   *
   * <code>string quoted_content_type = 4;</code>
   * @return The bytes for quotedContentType.
   */
  com.google.protobuf.ByteString
      getQuotedContentTypeBytes();

  /**
   * <pre>
   * 引用原因
   * </pre>
   *
   * <code>string quote_reason = 5;</code>
   * @return The quoteReason.
   */
  java.lang.String getQuoteReason();
  /**
   * <pre>
   * 引用原因
   * </pre>
   *
   * <code>string quote_reason = 5;</code>
   * @return The bytes for quoteReason.
   */
  com.google.protobuf.ByteString
      getQuoteReasonBytes();
}
