// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface SystemMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.SystemMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 系统消息类型
   * </pre>
   *
   * <code>string system_type = 1;</code>
   * @return The systemType.
   */
  java.lang.String getSystemType();
  /**
   * <pre>
   * 系统消息类型
   * </pre>
   *
   * <code>string system_type = 1;</code>
   * @return The bytes for systemType.
   */
  com.google.protobuf.ByteString
      getSystemTypeBytes();

  /**
   * <pre>
   * 系统消息内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 系统消息内容
   * </pre>
   *
   * <code>string content = 2;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 系统消息级别
   * </pre>
   *
   * <code>string level = 3;</code>
   * @return The level.
   */
  java.lang.String getLevel();
  /**
   * <pre>
   * 系统消息级别
   * </pre>
   *
   * <code>string level = 3;</code>
   * @return The bytes for level.
   */
  com.google.protobuf.ByteString
      getLevelBytes();

  /**
   * <pre>
   * 系统消息分类
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The category.
   */
  java.lang.String getCategory();
  /**
   * <pre>
   * 系统消息分类
   * </pre>
   *
   * <code>string category = 4;</code>
   * @return The bytes for category.
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <pre>
   * 系统消息动作
   * </pre>
   *
   * <code>string action = 5;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * 系统消息动作
   * </pre>
   *
   * <code>string action = 5;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * 动作参数（JSON字符串）
   * </pre>
   *
   * <code>string action_params = 6;</code>
   * @return The actionParams.
   */
  java.lang.String getActionParams();
  /**
   * <pre>
   * 动作参数（JSON字符串）
   * </pre>
   *
   * <code>string action_params = 6;</code>
   * @return The bytes for actionParams.
   */
  com.google.protobuf.ByteString
      getActionParamsBytes();

  /**
   * <pre>
   * 系统消息标签
   * </pre>
   *
   * <code>repeated string tags = 7;</code>
   * @return A list containing the tags.
   */
  java.util.List<java.lang.String>
      getTagsList();
  /**
   * <pre>
   * 系统消息标签
   * </pre>
   *
   * <code>repeated string tags = 7;</code>
   * @return The count of tags.
   */
  int getTagsCount();
  /**
   * <pre>
   * 系统消息标签
   * </pre>
   *
   * <code>repeated string tags = 7;</code>
   * @param index The index of the element to return.
   * @return The tags at the given index.
   */
  java.lang.String getTags(int index);
  /**
   * <pre>
   * 系统消息标签
   * </pre>
   *
   * <code>repeated string tags = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tags at the given index.
   */
  com.google.protobuf.ByteString
      getTagsBytes(int index);

  /**
   * <pre>
   * 过期时间
   * </pre>
   *
   * <code>int64 expires_at = 8;</code>
   * @return The expiresAt.
   */
  long getExpiresAt();
}
