// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public interface WebSocketMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.acme.im.websocket.WebSocketMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 消息ID（全局唯一）
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <pre>
   * 消息ID（全局唯一）
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageType type = 2;</code>
   * @return The type.
   */
  com.acme.im.common.websocket.proto.MessageType getType();

  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
   * @return The status.
   */
  com.acme.im.common.websocket.proto.MessageStatus getStatus();

  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string sender_id = 4;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string sender_id = 4;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <pre>
   * 接收者ID（用户ID或群组ID）
   * </pre>
   *
   * <code>string receiver_id = 5;</code>
   * @return The receiverId.
   */
  java.lang.String getReceiverId();
  /**
   * <pre>
   * 接收者ID（用户ID或群组ID）
   * </pre>
   *
   * <code>string receiver_id = 5;</code>
   * @return The bytes for receiverId.
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>string conversation_id = 6;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>string conversation_id = 6;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <pre>
   * 消息时间戳（Unix时间戳，毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 消息序列号（会话内唯一）
   * </pre>
   *
   * <code>int64 sequence = 8;</code>
   * @return The sequence.
   */
  long getSequence();

  /**
   * <pre>
   * 客户端消息ID（幂等性）
   * </pre>
   *
   * <code>string client_message_id = 9;</code>
   * @return The clientMessageId.
   */
  java.lang.String getClientMessageId();
  /**
   * <pre>
   * 客户端消息ID（幂等性）
   * </pre>
   *
   * <code>string client_message_id = 9;</code>
   * @return The bytes for clientMessageId.
   */
  com.google.protobuf.ByteString
      getClientMessageIdBytes();

  /**
   * <pre>
   * 消息版本
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * 消息版本
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * 设备ID（多端同步）
   * </pre>
   *
   * <code>string device_id = 11;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   * 设备ID（多端同步）
   * </pre>
   *
   * <code>string device_id = 11;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <pre>
   * 消息来源（web、mobile、desktop等）
   * </pre>
   *
   * <code>string source = 12;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <pre>
   * 消息来源（web、mobile、desktop等）
   * </pre>
   *
   * <code>string source = 12;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   * @return Whether the chat field is set.
   */
  boolean hasChat();
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   * @return The chat.
   */
  com.acme.im.common.websocket.proto.ChatMessage getChat();
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   */
  com.acme.im.common.websocket.proto.ChatMessageOrBuilder getChatOrBuilder();

  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   * @return Whether the notification field is set.
   */
  boolean hasNotification();
  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   * @return The notification.
   */
  com.acme.im.common.websocket.proto.NotificationMessage getNotification();
  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   */
  com.acme.im.common.websocket.proto.NotificationMessageOrBuilder getNotificationOrBuilder();

  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   * @return Whether the system field is set.
   */
  boolean hasSystem();
  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   * @return The system.
   */
  com.acme.im.common.websocket.proto.SystemMessage getSystem();
  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   */
  com.acme.im.common.websocket.proto.SystemMessageOrBuilder getSystemOrBuilder();

  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   * @return The event.
   */
  com.acme.im.common.websocket.proto.EventMessage getEvent();
  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   */
  com.acme.im.common.websocket.proto.EventMessageOrBuilder getEventOrBuilder();

  com.acme.im.common.websocket.proto.WebSocketMessage.PayloadCase getPayloadCase();
}
