// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

/**
 * <pre>
 **
 * WebSocket消息基础结构
 * 外层固定通用字段，扩展层包含特定字段
 * </pre>
 *
 * Protobuf type {@code com.acme.im.websocket.WebSocketMessage}
 */
public final class WebSocketMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.acme.im.websocket.WebSocketMessage)
    WebSocketMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WebSocketMessage.newBuilder() to construct.
  private WebSocketMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WebSocketMessage() {
    messageId_ = "";
    type_ = 0;
    status_ = 0;
    senderId_ = "";
    receiverId_ = "";
    conversationId_ = "";
    clientMessageId_ = "";
    version_ = "";
    deviceId_ = "";
    source_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WebSocketMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_WebSocketMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_WebSocketMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.acme.im.common.websocket.proto.WebSocketMessage.class, com.acme.im.common.websocket.proto.WebSocketMessage.Builder.class);
  }

  private int payloadCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object payload_;
  public enum PayloadCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CHAT(20),
    NOTIFICATION(21),
    SYSTEM(22),
    EVENT(23),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 20: return CHAT;
        case 21: return NOTIFICATION;
        case 22: return SYSTEM;
        case 23: return EVENT;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  public static final int MESSAGE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object messageId_ = "";
  /**
   * <pre>
   * 消息ID（全局唯一）
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  @java.lang.Override
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息ID（全局唯一）
   * </pre>
   *
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 消息类型
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public com.acme.im.common.websocket.proto.MessageType getType() {
    com.acme.im.common.websocket.proto.MessageType result = com.acme.im.common.websocket.proto.MessageType.forNumber(type_);
    return result == null ? com.acme.im.common.websocket.proto.MessageType.UNRECOGNIZED : result;
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_ = 0;
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
   * @return The status.
   */
  @java.lang.Override public com.acme.im.common.websocket.proto.MessageStatus getStatus() {
    com.acme.im.common.websocket.proto.MessageStatus result = com.acme.im.common.websocket.proto.MessageStatus.forNumber(status_);
    return result == null ? com.acme.im.common.websocket.proto.MessageStatus.UNRECOGNIZED : result;
  }

  public static final int SENDER_ID_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senderId_ = "";
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string sender_id = 4;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public java.lang.String getSenderId() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送者ID
   * </pre>
   *
   * <code>string sender_id = 4;</code>
   * @return The bytes for senderId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderIdBytes() {
    java.lang.Object ref = senderId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_ID_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object receiverId_ = "";
  /**
   * <pre>
   * 接收者ID（用户ID或群组ID）
   * </pre>
   *
   * <code>string receiver_id = 5;</code>
   * @return The receiverId.
   */
  @java.lang.Override
  public java.lang.String getReceiverId() {
    java.lang.Object ref = receiverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiverId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接收者ID（用户ID或群组ID）
   * </pre>
   *
   * <code>string receiver_id = 5;</code>
   * @return The bytes for receiverId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverIdBytes() {
    java.lang.Object ref = receiverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONVERSATION_ID_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object conversationId_ = "";
  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>string conversation_id = 6;</code>
   * @return The conversationId.
   */
  @java.lang.Override
  public java.lang.String getConversationId() {
    java.lang.Object ref = conversationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      conversationId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话ID
   * </pre>
   *
   * <code>string conversation_id = 6;</code>
   * @return The bytes for conversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIdBytes() {
    java.lang.Object ref = conversationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      conversationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_ = 0L;
  /**
   * <pre>
   * 消息时间戳（Unix时间戳，毫秒）
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int SEQUENCE_FIELD_NUMBER = 8;
  private long sequence_ = 0L;
  /**
   * <pre>
   * 消息序列号（会话内唯一）
   * </pre>
   *
   * <code>int64 sequence = 8;</code>
   * @return The sequence.
   */
  @java.lang.Override
  public long getSequence() {
    return sequence_;
  }

  public static final int CLIENT_MESSAGE_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientMessageId_ = "";
  /**
   * <pre>
   * 客户端消息ID（幂等性）
   * </pre>
   *
   * <code>string client_message_id = 9;</code>
   * @return The clientMessageId.
   */
  @java.lang.Override
  public java.lang.String getClientMessageId() {
    java.lang.Object ref = clientMessageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientMessageId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 客户端消息ID（幂等性）
   * </pre>
   *
   * <code>string client_message_id = 9;</code>
   * @return The bytes for clientMessageId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientMessageIdBytes() {
    java.lang.Object ref = clientMessageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientMessageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object version_ = "";
  /**
   * <pre>
   * 消息版本
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息版本
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <pre>
   * 设备ID（多端同步）
   * </pre>
   *
   * <code>string device_id = 11;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备ID（多端同步）
   * </pre>
   *
   * <code>string device_id = 11;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object source_ = "";
  /**
   * <pre>
   * 消息来源（web、mobile、desktop等）
   * </pre>
   *
   * <code>string source = 12;</code>
   * @return The source.
   */
  @java.lang.Override
  public java.lang.String getSource() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      source_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息来源（web、mobile、desktop等）
   * </pre>
   *
   * <code>string source = 12;</code>
   * @return The bytes for source.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSourceBytes() {
    java.lang.Object ref = source_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      source_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHAT_FIELD_NUMBER = 20;
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   * @return Whether the chat field is set.
   */
  @java.lang.Override
  public boolean hasChat() {
    return payloadCase_ == 20;
  }
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   * @return The chat.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.ChatMessage getChat() {
    if (payloadCase_ == 20) {
       return (com.acme.im.common.websocket.proto.ChatMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * 聊天消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.ChatMessageOrBuilder getChatOrBuilder() {
    if (payloadCase_ == 20) {
       return (com.acme.im.common.websocket.proto.ChatMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
  }

  public static final int NOTIFICATION_FIELD_NUMBER = 21;
  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   * @return Whether the notification field is set.
   */
  @java.lang.Override
  public boolean hasNotification() {
    return payloadCase_ == 21;
  }
  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   * @return The notification.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.NotificationMessage getNotification() {
    if (payloadCase_ == 21) {
       return (com.acme.im.common.websocket.proto.NotificationMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * 通知消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.NotificationMessageOrBuilder getNotificationOrBuilder() {
    if (payloadCase_ == 21) {
       return (com.acme.im.common.websocket.proto.NotificationMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
  }

  public static final int SYSTEM_FIELD_NUMBER = 22;
  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   * @return Whether the system field is set.
   */
  @java.lang.Override
  public boolean hasSystem() {
    return payloadCase_ == 22;
  }
  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   * @return The system.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.SystemMessage getSystem() {
    if (payloadCase_ == 22) {
       return (com.acme.im.common.websocket.proto.SystemMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * 系统消息
   * </pre>
   *
   * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.SystemMessageOrBuilder getSystemOrBuilder() {
    if (payloadCase_ == 22) {
       return (com.acme.im.common.websocket.proto.SystemMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
  }

  public static final int EVENT_FIELD_NUMBER = 23;
  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   * @return Whether the event field is set.
   */
  @java.lang.Override
  public boolean hasEvent() {
    return payloadCase_ == 23;
  }
  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   * @return The event.
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.EventMessage getEvent() {
    if (payloadCase_ == 23) {
       return (com.acme.im.common.websocket.proto.EventMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
  }
  /**
   * <pre>
   * NATS事件通知
   * </pre>
   *
   * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
   */
  @java.lang.Override
  public com.acme.im.common.websocket.proto.EventMessageOrBuilder getEventOrBuilder() {
    if (payloadCase_ == 23) {
       return (com.acme.im.common.websocket.proto.EventMessage) payload_;
    }
    return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageId_);
    }
    if (type_ != com.acme.im.common.websocket.proto.MessageType.CHAT_TEXT.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (status_ != com.acme.im.common.websocket.proto.MessageStatus.MESSAGE_DELETED.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, receiverId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, conversationId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (sequence_ != 0L) {
      output.writeInt64(8, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientMessageId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, clientMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, source_);
    }
    if (payloadCase_ == 20) {
      output.writeMessage(20, (com.acme.im.common.websocket.proto.ChatMessage) payload_);
    }
    if (payloadCase_ == 21) {
      output.writeMessage(21, (com.acme.im.common.websocket.proto.NotificationMessage) payload_);
    }
    if (payloadCase_ == 22) {
      output.writeMessage(22, (com.acme.im.common.websocket.proto.SystemMessage) payload_);
    }
    if (payloadCase_ == 23) {
      output.writeMessage(23, (com.acme.im.common.websocket.proto.EventMessage) payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageId_);
    }
    if (type_ != com.acme.im.common.websocket.proto.MessageType.CHAT_TEXT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (status_ != com.acme.im.common.websocket.proto.MessageStatus.MESSAGE_DELETED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, senderId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(receiverId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, receiverId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(conversationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, conversationId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (sequence_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, sequence_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientMessageId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, clientMessageId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, version_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(source_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, source_);
    }
    if (payloadCase_ == 20) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, (com.acme.im.common.websocket.proto.ChatMessage) payload_);
    }
    if (payloadCase_ == 21) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, (com.acme.im.common.websocket.proto.NotificationMessage) payload_);
    }
    if (payloadCase_ == 22) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(22, (com.acme.im.common.websocket.proto.SystemMessage) payload_);
    }
    if (payloadCase_ == 23) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(23, (com.acme.im.common.websocket.proto.EventMessage) payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.acme.im.common.websocket.proto.WebSocketMessage)) {
      return super.equals(obj);
    }
    com.acme.im.common.websocket.proto.WebSocketMessage other = (com.acme.im.common.websocket.proto.WebSocketMessage) obj;

    if (!getMessageId()
        .equals(other.getMessageId())) return false;
    if (type_ != other.type_) return false;
    if (status_ != other.status_) return false;
    if (!getSenderId()
        .equals(other.getSenderId())) return false;
    if (!getReceiverId()
        .equals(other.getReceiverId())) return false;
    if (!getConversationId()
        .equals(other.getConversationId())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getSequence()
        != other.getSequence()) return false;
    if (!getClientMessageId()
        .equals(other.getClientMessageId())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getSource()
        .equals(other.getSource())) return false;
    if (!getPayloadCase().equals(other.getPayloadCase())) return false;
    switch (payloadCase_) {
      case 20:
        if (!getChat()
            .equals(other.getChat())) return false;
        break;
      case 21:
        if (!getNotification()
            .equals(other.getNotification())) return false;
        break;
      case 22:
        if (!getSystem()
            .equals(other.getSystem())) return false;
        break;
      case 23:
        if (!getEvent()
            .equals(other.getEvent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMessageId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSenderId().hashCode();
    hash = (37 * hash) + RECEIVER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverId().hashCode();
    hash = (37 * hash) + CONVERSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getConversationId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSequence());
    hash = (37 * hash) + CLIENT_MESSAGE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientMessageId().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + getSource().hashCode();
    switch (payloadCase_) {
      case 20:
        hash = (37 * hash) + CHAT_FIELD_NUMBER;
        hash = (53 * hash) + getChat().hashCode();
        break;
      case 21:
        hash = (37 * hash) + NOTIFICATION_FIELD_NUMBER;
        hash = (53 * hash) + getNotification().hashCode();
        break;
      case 22:
        hash = (37 * hash) + SYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getSystem().hashCode();
        break;
      case 23:
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEvent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.acme.im.common.websocket.proto.WebSocketMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.acme.im.common.websocket.proto.WebSocketMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.acme.im.common.websocket.proto.WebSocketMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.acme.im.common.websocket.proto.WebSocketMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   **
   * WebSocket消息基础结构
   * 外层固定通用字段，扩展层包含特定字段
   * </pre>
   *
   * Protobuf type {@code com.acme.im.websocket.WebSocketMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.acme.im.websocket.WebSocketMessage)
      com.acme.im.common.websocket.proto.WebSocketMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_WebSocketMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_WebSocketMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.acme.im.common.websocket.proto.WebSocketMessage.class, com.acme.im.common.websocket.proto.WebSocketMessage.Builder.class);
    }

    // Construct using com.acme.im.common.websocket.proto.WebSocketMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      messageId_ = "";
      type_ = 0;
      status_ = 0;
      senderId_ = "";
      receiverId_ = "";
      conversationId_ = "";
      timestamp_ = 0L;
      sequence_ = 0L;
      clientMessageId_ = "";
      version_ = "";
      deviceId_ = "";
      source_ = "";
      if (chatBuilder_ != null) {
        chatBuilder_.clear();
      }
      if (notificationBuilder_ != null) {
        notificationBuilder_.clear();
      }
      if (systemBuilder_ != null) {
        systemBuilder_.clear();
      }
      if (eventBuilder_ != null) {
        eventBuilder_.clear();
      }
      payloadCase_ = 0;
      payload_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.acme.im.common.websocket.proto.WebSocketProto.internal_static_com_acme_im_websocket_WebSocketMessage_descriptor;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.WebSocketMessage getDefaultInstanceForType() {
      return com.acme.im.common.websocket.proto.WebSocketMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.WebSocketMessage build() {
      com.acme.im.common.websocket.proto.WebSocketMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.acme.im.common.websocket.proto.WebSocketMessage buildPartial() {
      com.acme.im.common.websocket.proto.WebSocketMessage result = new com.acme.im.common.websocket.proto.WebSocketMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.acme.im.common.websocket.proto.WebSocketMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.messageId_ = messageId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.senderId_ = senderId_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.receiverId_ = receiverId_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.conversationId_ = conversationId_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.timestamp_ = timestamp_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sequence_ = sequence_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.clientMessageId_ = clientMessageId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.source_ = source_;
      }
    }

    private void buildPartialOneofs(com.acme.im.common.websocket.proto.WebSocketMessage result) {
      result.payloadCase_ = payloadCase_;
      result.payload_ = this.payload_;
      if (payloadCase_ == 20 &&
          chatBuilder_ != null) {
        result.payload_ = chatBuilder_.build();
      }
      if (payloadCase_ == 21 &&
          notificationBuilder_ != null) {
        result.payload_ = notificationBuilder_.build();
      }
      if (payloadCase_ == 22 &&
          systemBuilder_ != null) {
        result.payload_ = systemBuilder_.build();
      }
      if (payloadCase_ == 23 &&
          eventBuilder_ != null) {
        result.payload_ = eventBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.acme.im.common.websocket.proto.WebSocketMessage) {
        return mergeFrom((com.acme.im.common.websocket.proto.WebSocketMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.acme.im.common.websocket.proto.WebSocketMessage other) {
      if (other == com.acme.im.common.websocket.proto.WebSocketMessage.getDefaultInstance()) return this;
      if (!other.getMessageId().isEmpty()) {
        messageId_ = other.messageId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getSenderId().isEmpty()) {
        senderId_ = other.senderId_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getReceiverId().isEmpty()) {
        receiverId_ = other.receiverId_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getConversationId().isEmpty()) {
        conversationId_ = other.conversationId_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getSequence() != 0L) {
        setSequence(other.getSequence());
      }
      if (!other.getClientMessageId().isEmpty()) {
        clientMessageId_ = other.clientMessageId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getSource().isEmpty()) {
        source_ = other.source_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      switch (other.getPayloadCase()) {
        case CHAT: {
          mergeChat(other.getChat());
          break;
        }
        case NOTIFICATION: {
          mergeNotification(other.getNotification());
          break;
        }
        case SYSTEM: {
          mergeSystem(other.getSystem());
          break;
        }
        case EVENT: {
          mergeEvent(other.getEvent());
          break;
        }
        case PAYLOAD_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              messageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              senderId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              receiverId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              conversationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              timestamp_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              sequence_ = input.readInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              clientMessageId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              version_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              source_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 162: {
              input.readMessage(
                  getChatFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 20;
              break;
            } // case 162
            case 170: {
              input.readMessage(
                  getNotificationFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 21;
              break;
            } // case 170
            case 178: {
              input.readMessage(
                  getSystemFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 22;
              break;
            } // case 178
            case 186: {
              input.readMessage(
                  getEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              payloadCase_ = 23;
              break;
            } // case 186
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public PayloadCase
        getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    public Builder clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object messageId_ = "";
    /**
     * <pre>
     * 消息ID（全局唯一）
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The messageId.
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息ID（全局唯一）
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return The bytes for messageId.
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息ID（全局唯一）
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID（全局唯一）
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageId() {
      messageId_ = getDefaultInstance().getMessageId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息ID（全局唯一）
     * </pre>
     *
     * <code>string message_id = 1;</code>
     * @param value The bytes for messageId to set.
     * @return This builder for chaining.
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.MessageType getType() {
      com.acme.im.common.websocket.proto.MessageType result = com.acme.im.common.websocket.proto.MessageType.forNumber(type_);
      return result == null ? com.acme.im.common.websocket.proto.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.acme.im.common.websocket.proto.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.MessageStatus getStatus() {
      com.acme.im.common.websocket.proto.MessageStatus result = com.acme.im.common.websocket.proto.MessageStatus.forNumber(status_);
      return result == null ? com.acme.im.common.websocket.proto.MessageStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.acme.im.common.websocket.proto.MessageStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.acme.im.websocket.MessageStatus status = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000004);
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object senderId_ = "";
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string sender_id = 4;</code>
     * @return The senderId.
     */
    public java.lang.String getSenderId() {
      java.lang.Object ref = senderId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string sender_id = 4;</code>
     * @return The bytes for senderId.
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      java.lang.Object ref = senderId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string sender_id = 4;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string sender_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      senderId_ = getDefaultInstance().getSenderId();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>string sender_id = 4;</code>
     * @param value The bytes for senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senderId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object receiverId_ = "";
    /**
     * <pre>
     * 接收者ID（用户ID或群组ID）
     * </pre>
     *
     * <code>string receiver_id = 5;</code>
     * @return The receiverId.
     */
    public java.lang.String getReceiverId() {
      java.lang.Object ref = receiverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 接收者ID（用户ID或群组ID）
     * </pre>
     *
     * <code>string receiver_id = 5;</code>
     * @return The bytes for receiverId.
     */
    public com.google.protobuf.ByteString
        getReceiverIdBytes() {
      java.lang.Object ref = receiverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接收者ID（用户ID或群组ID）
     * </pre>
     *
     * <code>string receiver_id = 5;</code>
     * @param value The receiverId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      receiverId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收者ID（用户ID或群组ID）
     * </pre>
     *
     * <code>string receiver_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverId() {
      receiverId_ = getDefaultInstance().getReceiverId();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收者ID（用户ID或群组ID）
     * </pre>
     *
     * <code>string receiver_id = 5;</code>
     * @param value The bytes for receiverId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      receiverId_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object conversationId_ = "";
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string conversation_id = 6;</code>
     * @return The conversationId.
     */
    public java.lang.String getConversationId() {
      java.lang.Object ref = conversationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        conversationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string conversation_id = 6;</code>
     * @return The bytes for conversationId.
     */
    public com.google.protobuf.ByteString
        getConversationIdBytes() {
      java.lang.Object ref = conversationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        conversationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string conversation_id = 6;</code>
     * @param value The conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      conversationId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string conversation_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationId() {
      conversationId_ = getDefaultInstance().getConversationId();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话ID
     * </pre>
     *
     * <code>string conversation_id = 6;</code>
     * @param value The bytes for conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      conversationId_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 消息时间戳（Unix时间戳，毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 消息时间戳（Unix时间戳，毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {

      timestamp_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息时间戳（Unix时间戳，毫秒）
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000040);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long sequence_ ;
    /**
     * <pre>
     * 消息序列号（会话内唯一）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public long getSequence() {
      return sequence_;
    }
    /**
     * <pre>
     * 消息序列号（会话内唯一）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @param value The sequence to set.
     * @return This builder for chaining.
     */
    public Builder setSequence(long value) {

      sequence_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息序列号（会话内唯一）
     * </pre>
     *
     * <code>int64 sequence = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSequence() {
      bitField0_ = (bitField0_ & ~0x00000080);
      sequence_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object clientMessageId_ = "";
    /**
     * <pre>
     * 客户端消息ID（幂等性）
     * </pre>
     *
     * <code>string client_message_id = 9;</code>
     * @return The clientMessageId.
     */
    public java.lang.String getClientMessageId() {
      java.lang.Object ref = clientMessageId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientMessageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 客户端消息ID（幂等性）
     * </pre>
     *
     * <code>string client_message_id = 9;</code>
     * @return The bytes for clientMessageId.
     */
    public com.google.protobuf.ByteString
        getClientMessageIdBytes() {
      java.lang.Object ref = clientMessageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 客户端消息ID（幂等性）
     * </pre>
     *
     * <code>string client_message_id = 9;</code>
     * @param value The clientMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setClientMessageId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientMessageId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端消息ID（幂等性）
     * </pre>
     *
     * <code>string client_message_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientMessageId() {
      clientMessageId_ = getDefaultInstance().getClientMessageId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 客户端消息ID（幂等性）
     * </pre>
     *
     * <code>string client_message_id = 9;</code>
     * @param value The bytes for clientMessageId to set.
     * @return This builder for chaining.
     */
    public Builder setClientMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientMessageId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     * 消息版本
     * </pre>
     *
     * <code>string version = 10;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息版本
     * </pre>
     *
     * <code>string version = 10;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息版本
     * </pre>
     *
     * <code>string version = 10;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      version_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息版本
     * </pre>
     *
     * <code>string version = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      version_ = getDefaultInstance().getVersion();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息版本
     * </pre>
     *
     * <code>string version = 10;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      version_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <pre>
     * 设备ID（多端同步）
     * </pre>
     *
     * <code>string device_id = 11;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备ID（多端同步）
     * </pre>
     *
     * <code>string device_id = 11;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备ID（多端同步）
     * </pre>
     *
     * <code>string device_id = 11;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID（多端同步）
     * </pre>
     *
     * <code>string device_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备ID（多端同步）
     * </pre>
     *
     * <code>string device_id = 11;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object source_ = "";
    /**
     * <pre>
     * 消息来源（web、mobile、desktop等）
     * </pre>
     *
     * <code>string source = 12;</code>
     * @return The source.
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息来源（web、mobile、desktop等）
     * </pre>
     *
     * <code>string source = 12;</code>
     * @return The bytes for source.
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息来源（web、mobile、desktop等）
     * </pre>
     *
     * <code>string source = 12;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      source_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息来源（web、mobile、desktop等）
     * </pre>
     *
     * <code>string source = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      source_ = getDefaultInstance().getSource();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息来源（web、mobile、desktop等）
     * </pre>
     *
     * <code>string source = 12;</code>
     * @param value The bytes for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      source_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.ChatMessage, com.acme.im.common.websocket.proto.ChatMessage.Builder, com.acme.im.common.websocket.proto.ChatMessageOrBuilder> chatBuilder_;
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     * @return Whether the chat field is set.
     */
    @java.lang.Override
    public boolean hasChat() {
      return payloadCase_ == 20;
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     * @return The chat.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.ChatMessage getChat() {
      if (chatBuilder_ == null) {
        if (payloadCase_ == 20) {
          return (com.acme.im.common.websocket.proto.ChatMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 20) {
          return chatBuilder_.getMessage();
        }
        return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    public Builder setChat(com.acme.im.common.websocket.proto.ChatMessage value) {
      if (chatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        chatBuilder_.setMessage(value);
      }
      payloadCase_ = 20;
      return this;
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    public Builder setChat(
        com.acme.im.common.websocket.proto.ChatMessage.Builder builderForValue) {
      if (chatBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        chatBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 20;
      return this;
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    public Builder mergeChat(com.acme.im.common.websocket.proto.ChatMessage value) {
      if (chatBuilder_ == null) {
        if (payloadCase_ == 20 &&
            payload_ != com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance()) {
          payload_ = com.acme.im.common.websocket.proto.ChatMessage.newBuilder((com.acme.im.common.websocket.proto.ChatMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 20) {
          chatBuilder_.mergeFrom(value);
        } else {
          chatBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 20;
      return this;
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    public Builder clearChat() {
      if (chatBuilder_ == null) {
        if (payloadCase_ == 20) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 20) {
          payloadCase_ = 0;
          payload_ = null;
        }
        chatBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    public com.acme.im.common.websocket.proto.ChatMessage.Builder getChatBuilder() {
      return getChatFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.ChatMessageOrBuilder getChatOrBuilder() {
      if ((payloadCase_ == 20) && (chatBuilder_ != null)) {
        return chatBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 20) {
          return (com.acme.im.common.websocket.proto.ChatMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 聊天消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.ChatMessage chat = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.ChatMessage, com.acme.im.common.websocket.proto.ChatMessage.Builder, com.acme.im.common.websocket.proto.ChatMessageOrBuilder> 
        getChatFieldBuilder() {
      if (chatBuilder_ == null) {
        if (!(payloadCase_ == 20)) {
          payload_ = com.acme.im.common.websocket.proto.ChatMessage.getDefaultInstance();
        }
        chatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.ChatMessage, com.acme.im.common.websocket.proto.ChatMessage.Builder, com.acme.im.common.websocket.proto.ChatMessageOrBuilder>(
                (com.acme.im.common.websocket.proto.ChatMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 20;
      onChanged();
      return chatBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.NotificationMessage, com.acme.im.common.websocket.proto.NotificationMessage.Builder, com.acme.im.common.websocket.proto.NotificationMessageOrBuilder> notificationBuilder_;
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     * @return Whether the notification field is set.
     */
    @java.lang.Override
    public boolean hasNotification() {
      return payloadCase_ == 21;
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     * @return The notification.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.NotificationMessage getNotification() {
      if (notificationBuilder_ == null) {
        if (payloadCase_ == 21) {
          return (com.acme.im.common.websocket.proto.NotificationMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 21) {
          return notificationBuilder_.getMessage();
        }
        return com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    public Builder setNotification(com.acme.im.common.websocket.proto.NotificationMessage value) {
      if (notificationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        notificationBuilder_.setMessage(value);
      }
      payloadCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    public Builder setNotification(
        com.acme.im.common.websocket.proto.NotificationMessage.Builder builderForValue) {
      if (notificationBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        notificationBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    public Builder mergeNotification(com.acme.im.common.websocket.proto.NotificationMessage value) {
      if (notificationBuilder_ == null) {
        if (payloadCase_ == 21 &&
            payload_ != com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance()) {
          payload_ = com.acme.im.common.websocket.proto.NotificationMessage.newBuilder((com.acme.im.common.websocket.proto.NotificationMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 21) {
          notificationBuilder_.mergeFrom(value);
        } else {
          notificationBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 21;
      return this;
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    public Builder clearNotification() {
      if (notificationBuilder_ == null) {
        if (payloadCase_ == 21) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 21) {
          payloadCase_ = 0;
          payload_ = null;
        }
        notificationBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    public com.acme.im.common.websocket.proto.NotificationMessage.Builder getNotificationBuilder() {
      return getNotificationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.NotificationMessageOrBuilder getNotificationOrBuilder() {
      if ((payloadCase_ == 21) && (notificationBuilder_ != null)) {
        return notificationBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 21) {
          return (com.acme.im.common.websocket.proto.NotificationMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 通知消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.NotificationMessage notification = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.NotificationMessage, com.acme.im.common.websocket.proto.NotificationMessage.Builder, com.acme.im.common.websocket.proto.NotificationMessageOrBuilder> 
        getNotificationFieldBuilder() {
      if (notificationBuilder_ == null) {
        if (!(payloadCase_ == 21)) {
          payload_ = com.acme.im.common.websocket.proto.NotificationMessage.getDefaultInstance();
        }
        notificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.NotificationMessage, com.acme.im.common.websocket.proto.NotificationMessage.Builder, com.acme.im.common.websocket.proto.NotificationMessageOrBuilder>(
                (com.acme.im.common.websocket.proto.NotificationMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 21;
      onChanged();
      return notificationBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.SystemMessage, com.acme.im.common.websocket.proto.SystemMessage.Builder, com.acme.im.common.websocket.proto.SystemMessageOrBuilder> systemBuilder_;
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     * @return Whether the system field is set.
     */
    @java.lang.Override
    public boolean hasSystem() {
      return payloadCase_ == 22;
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     * @return The system.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.SystemMessage getSystem() {
      if (systemBuilder_ == null) {
        if (payloadCase_ == 22) {
          return (com.acme.im.common.websocket.proto.SystemMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 22) {
          return systemBuilder_.getMessage();
        }
        return com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    public Builder setSystem(com.acme.im.common.websocket.proto.SystemMessage value) {
      if (systemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        systemBuilder_.setMessage(value);
      }
      payloadCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    public Builder setSystem(
        com.acme.im.common.websocket.proto.SystemMessage.Builder builderForValue) {
      if (systemBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        systemBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    public Builder mergeSystem(com.acme.im.common.websocket.proto.SystemMessage value) {
      if (systemBuilder_ == null) {
        if (payloadCase_ == 22 &&
            payload_ != com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance()) {
          payload_ = com.acme.im.common.websocket.proto.SystemMessage.newBuilder((com.acme.im.common.websocket.proto.SystemMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 22) {
          systemBuilder_.mergeFrom(value);
        } else {
          systemBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 22;
      return this;
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    public Builder clearSystem() {
      if (systemBuilder_ == null) {
        if (payloadCase_ == 22) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 22) {
          payloadCase_ = 0;
          payload_ = null;
        }
        systemBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    public com.acme.im.common.websocket.proto.SystemMessage.Builder getSystemBuilder() {
      return getSystemFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.SystemMessageOrBuilder getSystemOrBuilder() {
      if ((payloadCase_ == 22) && (systemBuilder_ != null)) {
        return systemBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 22) {
          return (com.acme.im.common.websocket.proto.SystemMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 系统消息
     * </pre>
     *
     * <code>.com.acme.im.websocket.SystemMessage system = 22;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.SystemMessage, com.acme.im.common.websocket.proto.SystemMessage.Builder, com.acme.im.common.websocket.proto.SystemMessageOrBuilder> 
        getSystemFieldBuilder() {
      if (systemBuilder_ == null) {
        if (!(payloadCase_ == 22)) {
          payload_ = com.acme.im.common.websocket.proto.SystemMessage.getDefaultInstance();
        }
        systemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.SystemMessage, com.acme.im.common.websocket.proto.SystemMessage.Builder, com.acme.im.common.websocket.proto.SystemMessageOrBuilder>(
                (com.acme.im.common.websocket.proto.SystemMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 22;
      onChanged();
      return systemBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.EventMessage, com.acme.im.common.websocket.proto.EventMessage.Builder, com.acme.im.common.websocket.proto.EventMessageOrBuilder> eventBuilder_;
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     * @return Whether the event field is set.
     */
    @java.lang.Override
    public boolean hasEvent() {
      return payloadCase_ == 23;
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     * @return The event.
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.EventMessage getEvent() {
      if (eventBuilder_ == null) {
        if (payloadCase_ == 23) {
          return (com.acme.im.common.websocket.proto.EventMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
      } else {
        if (payloadCase_ == 23) {
          return eventBuilder_.getMessage();
        }
        return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    public Builder setEvent(com.acme.im.common.websocket.proto.EventMessage value) {
      if (eventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        payload_ = value;
        onChanged();
      } else {
        eventBuilder_.setMessage(value);
      }
      payloadCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    public Builder setEvent(
        com.acme.im.common.websocket.proto.EventMessage.Builder builderForValue) {
      if (eventBuilder_ == null) {
        payload_ = builderForValue.build();
        onChanged();
      } else {
        eventBuilder_.setMessage(builderForValue.build());
      }
      payloadCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    public Builder mergeEvent(com.acme.im.common.websocket.proto.EventMessage value) {
      if (eventBuilder_ == null) {
        if (payloadCase_ == 23 &&
            payload_ != com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance()) {
          payload_ = com.acme.im.common.websocket.proto.EventMessage.newBuilder((com.acme.im.common.websocket.proto.EventMessage) payload_)
              .mergeFrom(value).buildPartial();
        } else {
          payload_ = value;
        }
        onChanged();
      } else {
        if (payloadCase_ == 23) {
          eventBuilder_.mergeFrom(value);
        } else {
          eventBuilder_.setMessage(value);
        }
      }
      payloadCase_ = 23;
      return this;
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    public Builder clearEvent() {
      if (eventBuilder_ == null) {
        if (payloadCase_ == 23) {
          payloadCase_ = 0;
          payload_ = null;
          onChanged();
        }
      } else {
        if (payloadCase_ == 23) {
          payloadCase_ = 0;
          payload_ = null;
        }
        eventBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    public com.acme.im.common.websocket.proto.EventMessage.Builder getEventBuilder() {
      return getEventFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    @java.lang.Override
    public com.acme.im.common.websocket.proto.EventMessageOrBuilder getEventOrBuilder() {
      if ((payloadCase_ == 23) && (eventBuilder_ != null)) {
        return eventBuilder_.getMessageOrBuilder();
      } else {
        if (payloadCase_ == 23) {
          return (com.acme.im.common.websocket.proto.EventMessage) payload_;
        }
        return com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * NATS事件通知
     * </pre>
     *
     * <code>.com.acme.im.websocket.EventMessage event = 23;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.acme.im.common.websocket.proto.EventMessage, com.acme.im.common.websocket.proto.EventMessage.Builder, com.acme.im.common.websocket.proto.EventMessageOrBuilder> 
        getEventFieldBuilder() {
      if (eventBuilder_ == null) {
        if (!(payloadCase_ == 23)) {
          payload_ = com.acme.im.common.websocket.proto.EventMessage.getDefaultInstance();
        }
        eventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.acme.im.common.websocket.proto.EventMessage, com.acme.im.common.websocket.proto.EventMessage.Builder, com.acme.im.common.websocket.proto.EventMessageOrBuilder>(
                (com.acme.im.common.websocket.proto.EventMessage) payload_,
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      payloadCase_ = 23;
      onChanged();
      return eventBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.acme.im.websocket.WebSocketMessage)
  }

  // @@protoc_insertion_point(class_scope:com.acme.im.websocket.WebSocketMessage)
  private static final com.acme.im.common.websocket.proto.WebSocketMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.acme.im.common.websocket.proto.WebSocketMessage();
  }

  public static com.acme.im.common.websocket.proto.WebSocketMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WebSocketMessage>
      PARSER = new com.google.protobuf.AbstractParser<WebSocketMessage>() {
    @java.lang.Override
    public WebSocketMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WebSocketMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WebSocketMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.acme.im.common.websocket.proto.WebSocketMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

