// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: websocket.proto

// Protobuf Java Version: 3.25.1
package com.acme.im.common.websocket.proto;

public final class WebSocketProto {
  private WebSocketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_WebSocketMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_WebSocketMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_QuoteInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_QuoteInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_ForwardInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_ForwardInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_EditInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_EditInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_NotificationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_NotificationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_SystemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_SystemMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_acme_im_websocket_EventMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_acme_im_websocket_EventMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017websocket.proto\022\025com.acme.im.websocket" +
      "\"\264\004\n\020WebSocketMessage\022\022\n\nmessage_id\030\001 \001(" +
      "\t\0220\n\004type\030\002 \001(\0162\".com.acme.im.websocket." +
      "MessageType\0224\n\006status\030\003 \001(\0162$.com.acme.i" +
      "m.websocket.MessageStatus\022\021\n\tsender_id\030\004" +
      " \001(\t\022\023\n\013receiver_id\030\005 \001(\t\022\027\n\017conversatio" +
      "n_id\030\006 \001(\t\022\021\n\ttimestamp\030\007 \001(\003\022\020\n\010sequenc" +
      "e\030\010 \001(\003\022\031\n\021client_message_id\030\t \001(\t\022\017\n\007ve" +
      "rsion\030\n \001(\t\022\021\n\tdevice_id\030\013 \001(\t\022\016\n\006source" +
      "\030\014 \001(\t\0222\n\004chat\030\024 \001(\0132\".com.acme.im.webso" +
      "cket.ChatMessageH\000\022B\n\014notification\030\025 \001(\013" +
      "2*.com.acme.im.websocket.NotificationMes" +
      "sageH\000\0226\n\006system\030\026 \001(\0132$.com.acme.im.web" +
      "socket.SystemMessageH\000\0224\n\005event\030\027 \001(\0132#." +
      "com.acme.im.websocket.EventMessageH\000B\t\n\007" +
      "payload\"\353\002\n\013ChatMessage\022\017\n\007content\030\001 \001(\t" +
      "\022\024\n\014content_type\030\002 \001(\t\022\025\n\rcontent_extra\030" +
      "\003 \001(\t\022\033\n\023original_message_id\030\004 \001(\t\022\026\n\016op" +
      "eration_type\030\005 \001(\t\0224\n\nquote_info\030\006 \001(\0132 " +
      ".com.acme.im.websocket.QuoteInfo\0228\n\014forw" +
      "ard_info\030\007 \001(\0132\".com.acme.im.websocket.F" +
      "orwardInfo\0222\n\tedit_info\030\010 \001(\0132\037.com.acme" +
      ".im.websocket.EditInfo\022\023\n\013reply_to_id\030\t " +
      "\001(\t\022\020\n\010mentions\030\n \001(\t\022\014\n\004tags\030\013 \003(\t\022\020\n\010p" +
      "riority\030\014 \001(\005\"\213\001\n\tQuoteInfo\022\031\n\021quoted_me" +
      "ssage_id\030\001 \001(\t\022\026\n\016quoted_content\030\002 \001(\t\022\030" +
      "\n\020quoted_sender_id\030\003 \001(\t\022\033\n\023quoted_conte" +
      "nt_type\030\004 \001(\t\022\024\n\014quote_reason\030\005 \001(\t\"z\n\013F" +
      "orwardInfo\022 \n\030original_conversation_id\030\001" +
      " \001(\t\022\032\n\022original_sender_id\030\002 \001(\t\022\026\n\016forw" +
      "ard_reason\030\003 \001(\t\022\025\n\rforward_chain\030\004 \003(\t\"" +
      "e\n\010EditInfo\022\030\n\020original_content\030\001 \001(\t\022\023\n" +
      "\013edit_reason\030\002 \001(\t\022\022\n\nedit_count\030\003 \001(\005\022\026" +
      "\n\016last_edit_time\030\004 \001(\003\"\324\001\n\023NotificationM" +
      "essage\022\r\n\005title\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022\031" +
      "\n\021notification_type\030\003 \001(\t\022\r\n\005level\030\004 \001(\t" +
      "\022\020\n\010category\030\005 \001(\t\022\016\n\006action\030\006 \001(\t\022\022\n\nac" +
      "tion_url\030\007 \001(\t\022\014\n\004icon\030\010 \001(\t\022\r\n\005image\030\t " +
      "\001(\t\022\014\n\004tags\030\n \003(\t\022\022\n\nexpires_at\030\013 \001(\003\"\237\001" +
      "\n\rSystemMessage\022\023\n\013system_type\030\001 \001(\t\022\017\n\007" +
      "content\030\002 \001(\t\022\r\n\005level\030\003 \001(\t\022\020\n\010category" +
      "\030\004 \001(\t\022\016\n\006action\030\005 \001(\t\022\025\n\raction_params\030" +
      "\006 \001(\t\022\014\n\004tags\030\007 \003(\t\022\022\n\nexpires_at\030\010 \001(\003\"" +
      "\275\001\n\014EventMessage\022\022\n\nevent_type\030\001 \001(\t\022\022\n\n" +
      "event_name\030\002 \001(\t\022\022\n\nevent_data\030\003 \001(\t\022\024\n\014" +
      "event_source\030\004 \001(\t\022\022\n\nevent_time\030\005 \001(\003\022\020" +
      "\n\010event_id\030\006 \001(\t\022\025\n\revent_version\030\007 \001(\t\022" +
      "\014\n\004tags\030\010 \003(\t\022\020\n\010metadata\030\t \001(\t*\214\004\n\013Mess" +
      "ageType\022\r\n\tCHAT_TEXT\020\000\022\016\n\nCHAT_IMAGE\020\001\022\r" +
      "\n\tCHAT_FILE\020\002\022\016\n\nCHAT_VOICE\020\003\022\016\n\nCHAT_VI" +
      "DEO\020\004\022\021\n\rCHAT_LOCATION\020\005\022\r\n\tCHAT_CARD\020\006\022" +
      "\r\n\tCHAT_EDIT\020\n\022\016\n\nCHAT_QUOTE\020\013\022\020\n\014CHAT_F" +
      "ORWARD\020\014\022\017\n\013CHAT_RECALL\020\r\022\035\n\031NOTIFICATIO" +
      "N_ANNOUNCEMENT\020\024\022\026\n\022NOTIFICATION_ALERT\020\025" +
      "\022\032\n\026NOTIFICATION_PROMOTION\020\026\022\034\n\030NOTIFICA" +
      "TION_MAINTENANCE\020\027\022\022\n\016SYSTEM_CONNECT\020\036\022\025" +
      "\n\021SYSTEM_DISCONNECT\020\037\022\024\n\020SYSTEM_HEARTBEA" +
      "T\020 \022\017\n\013SYSTEM_AUTH\020!\022\021\n\rSYSTEM_STATUS\020\"\022" +
      "\034\n\030EVENT_USER_STATUS_CHANGE\020(\022\026\n\022EVENT_G" +
      "ROUP_UPDATE\020)\022\037\n\033EVENT_MESSAGE_STATUS_CH" +
      "ANGE\020*\022\036\n\032EVENT_SYSTEM_CONFIG_CHANGE\020+*c" +
      "\n\rMessageStatus\022\023\n\017MESSAGE_DELETED\020\000\022\022\n\016" +
      "MESSAGE_NORMAL\020\001\022\023\n\017MESSAGE_PENDING\020\002\022\024\n" +
      "\020MESSAGE_REJECTED\020\003B6\n\"com.acme.im.commo" +
      "n.websocket.protoB\016WebSocketProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_acme_im_websocket_WebSocketMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_acme_im_websocket_WebSocketMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_WebSocketMessage_descriptor,
        new java.lang.String[] { "MessageId", "Type", "Status", "SenderId", "ReceiverId", "ConversationId", "Timestamp", "Sequence", "ClientMessageId", "Version", "DeviceId", "Source", "Chat", "Notification", "System", "Event", "Payload", });
    internal_static_com_acme_im_websocket_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_acme_im_websocket_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_ChatMessage_descriptor,
        new java.lang.String[] { "Content", "ContentType", "ContentExtra", "OriginalMessageId", "OperationType", "QuoteInfo", "ForwardInfo", "EditInfo", "ReplyToId", "Mentions", "Tags", "Priority", });
    internal_static_com_acme_im_websocket_QuoteInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_acme_im_websocket_QuoteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_QuoteInfo_descriptor,
        new java.lang.String[] { "QuotedMessageId", "QuotedContent", "QuotedSenderId", "QuotedContentType", "QuoteReason", });
    internal_static_com_acme_im_websocket_ForwardInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_acme_im_websocket_ForwardInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_ForwardInfo_descriptor,
        new java.lang.String[] { "OriginalConversationId", "OriginalSenderId", "ForwardReason", "ForwardChain", });
    internal_static_com_acme_im_websocket_EditInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_acme_im_websocket_EditInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_EditInfo_descriptor,
        new java.lang.String[] { "OriginalContent", "EditReason", "EditCount", "LastEditTime", });
    internal_static_com_acme_im_websocket_NotificationMessage_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_acme_im_websocket_NotificationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_NotificationMessage_descriptor,
        new java.lang.String[] { "Title", "Content", "NotificationType", "Level", "Category", "Action", "ActionUrl", "Icon", "Image", "Tags", "ExpiresAt", });
    internal_static_com_acme_im_websocket_SystemMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_acme_im_websocket_SystemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_SystemMessage_descriptor,
        new java.lang.String[] { "SystemType", "Content", "Level", "Category", "Action", "ActionParams", "Tags", "ExpiresAt", });
    internal_static_com_acme_im_websocket_EventMessage_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_acme_im_websocket_EventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_acme_im_websocket_EventMessage_descriptor,
        new java.lang.String[] { "EventType", "EventName", "EventData", "EventSource", "EventTime", "EventId", "EventVersion", "Tags", "Metadata", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
