server:
  port: 8080

spring:
  application:
    name: business-service
  
  # 引用公共配置 - 继承所有基础配置
  profiles:
    include: common
  
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

# 业务服务特有配置 - 只配置业务相关的
app:
  business:
    # 业务模块配置
    modules:
      user:
        enabled: true
        cache-ttl: 3600s
      social:
        enabled: true
        friend-request-expire: 7d
      group:
        enabled: true
        max-members: 500
      message:
        enabled: true
        max-retention: 30d
      file:
        enabled: true
        max-size: 100MB
      search:
        enabled: true
        max-results: 100
    
    # 业务限流配置
    rate-limit:
      user-operation: 100/minute
      group-operation: 50/minute
      file-upload: 10/minute
    
    # 业务缓存配置
    cache:
      user-profile: 1h
      group-info: 30m
      friend-list: 15m 