server:
  port: 8081

spring:
  application:
    name: business-service
  
  # 引用公共配置
  profiles:
    include: common
  
  main:
    allow-bean-definition-overriding: true
  
  # 服务特有的数据库配置
  # 使用公共模块的MyBatis-Plus配置，无需额外配置

# 业务服务特有配置
app:
  security:
    password-encoder-strength: 12
  
  # 数据源策略配置
  datasource:
    strategy: "auto"  # auto: 自动选择, primary: 强制主库, secondary: 强制从库
    # 读操作默认使用从库，写操作使用主库
    read-write-split: true 